/**
 * 模板示例数据。
 * 复制模板后，必须根据目标仓库的真实代码整体替换本文件。
 */
export const mapData = {
  directories: [
    {
      id: 'dir-src',
      name: 'src',
      description: '示例业务源码根目录。',
      parentId: null,
    },
    {
      id: 'dir-services',
      name: 'services',
      description: '示例业务能力层：负责校验和数据读取。',
      parentId: 'dir-src',
    },
    {
      id: 'dir-tasks',
      name: 'tasks',
      description: '示例业务编排层：保存唯一功能入口。',
      parentId: 'dir-src',
    },
    {
      id: 'dir-storage',
      name: 'storage',
      description: '示例结果边界：负责保存结果和记录失败。',
      parentId: 'dir-src',
    },
  ],
  files: [
    {
      id: 'file-feature-task',
      directoryId: 'dir-tasks',
      name: 'feature_task.py',
      path: 'src/tasks/feature_task.py',
      description: '示例功能入口和核心执行顺序。',
    },
    {
      id: 'file-feature-service',
      directoryId: 'dir-services',
      name: 'feature_service.py',
      path: 'src/services/feature_service.py',
      description: '示例输入校验和数据读取能力。',
    },
    {
      id: 'file-feature-storage',
      directoryId: 'dir-storage',
      name: 'feature_storage.py',
      path: 'src/storage/feature_storage.py',
      description: '示例结果保存和失败记录能力。',
    },
  ],
  methods: [
    {
      id: 'task-run-feature',
      fileId: 'file-feature-task',
      signature: 'run_feature(request: FeatureRequest) -> FeatureResult',
      meaning: '唯一功能入口：校验请求、读取数据并保存结果。',
      inputs: [
        {
          name: 'request',
          summary: '本次功能执行所需的请求对象。',
          detail: '复杂对象先用一句话说明用途，再在详细提示中解释来源、关键字段、单位和特殊值。',
        },
      ],
      output: {
        summary: '返回 FeatureResult，描述本次执行是否成功以及生成了什么。',
        fields: [
          { name: 'success', summary: '功能是否成功完成。' },
          { name: 'output_path', summary: '成功时生成结果文件的路径；没有文件时为 None。' },
        ],
      },
      source: { path: 'src/tasks/feature_task.py', startLine: 15, endLine: 48 },
      defaultExpanded: true,
      steps: [
        {
          id: 'run-validate',
          text: '1. 调用 validate_request() 校验影响业务结果的输入；无效请求在继续处理前报错。',
          tone: 'condition',
        },
        {
          id: 'run-load',
          text: '2. 调用 load_data() 读取本次处理需要的数据。',
          tone: 'normal',
        },
        {
          id: 'run-save',
          text: '3. 数据满足保存条件时调用 save_result() 写入最终结果。',
          tone: 'condition',
        },
        {
          id: 'run-error',
          text: '4. 如果执行失败，调用 report_failure() 记录可交付的失败原因，然后继续抛出原异常。',
          tone: 'error',
        },
      ],
    },
    {
      id: 'service-validate-request',
      fileId: 'file-feature-service',
      signature: 'validate_request(request: FeatureRequest) -> None',
      meaning: '检查请求是否满足功能执行条件。',
      inputs: [{ name: 'request', summary: '等待校验的功能请求。' }],
      output: { summary: '无返回值；校验失败时抛出异常。' },
      source: { path: 'src/services/feature_service.py', startLine: 8, endLine: 14 },
      defaultExpanded: false,
      steps: [
        { id: 'validate-required', text: '1. 检查业务必填字段和允许范围。', tone: 'condition' },
        { id: 'validate-error', text: '2. 发现无效数据时抛出带明确原因的异常。', tone: 'error' },
      ],
    },
    {
      id: 'service-load-data',
      fileId: 'file-feature-service',
      signature: 'load_data(request: FeatureRequest) -> list[Record]',
      meaning: '根据请求读取待处理数据。',
      inputs: [{ name: 'request', summary: '包含数据来源的功能请求。' }],
      output: { summary: '返回按业务顺序排列的记录列表。' },
      source: { path: 'src/services/feature_service.py', startLine: 17, endLine: 25 },
      defaultExpanded: false,
      steps: [
        { id: 'load-source', text: '1. 根据请求确定真实数据来源。', tone: 'condition' },
        { id: 'load-records', text: '2. 读取本次需要处理的原始记录。', tone: 'normal' },
        { id: 'load-normalize', text: '3. 调用 normalize_records() 统一记录顺序和字段格式。', tone: 'normal' },
      ],
    },
    {
      id: 'service-normalize-records',
      fileId: 'file-feature-service',
      signature: 'normalize_records(records: list[Record]) -> list[Record]',
      meaning: '统一示例记录的顺序和字段格式。',
      inputs: [{ name: 'records', summary: '刚从真实数据来源读取的原始记录。' }],
      output: { summary: '返回可以交给后续保存流程的标准记录列表。' },
      source: { path: 'src/services/feature_service.py', startLine: 28, endLine: 34 },
      defaultExpanded: false,
      steps: [
        { id: 'normalize-fields', text: '1. 逐条整理业务需要的字段。', tone: 'loop' },
        { id: 'normalize-order', text: '2. 按真实业务规则排序并返回全部记录。', tone: 'normal' },
      ],
    },
    {
      id: 'storage-save-result',
      fileId: 'file-feature-storage',
      signature: 'save_result(records: list[Record]) -> Path',
      meaning: '把处理结果保存到文件。',
      inputs: [{ name: 'records', summary: '已经完成处理、等待保存的记录。' }],
      output: { summary: '返回最终结果文件路径。' },
      source: { path: 'src/storage/feature_storage.py', startLine: 9, endLine: 17 },
      defaultExpanded: false,
      steps: [
        { id: 'save-create', text: '1. 创建结果目录并确定文件名。', tone: 'normal' },
        { id: 'save-write', text: '2. 按目标格式写入全部记录并返回路径。', tone: 'loop' },
      ],
    },
    {
      id: 'storage-report-failure',
      fileId: 'file-feature-storage',
      signature: 'report_failure(error: Exception) -> None',
      meaning: '记录功能失败时需要交付给用户的信息。',
      inputs: [{ name: 'error', summary: '核心流程捕获到的原始异常。' }],
      output: { summary: '无返回值；完成失败信息记录。' },
      source: { path: 'src/storage/feature_storage.py', startLine: 20, endLine: 25 },
      defaultExpanded: false,
      steps: [
        { id: 'failure-format', text: '1. 提取不包含敏感信息的失败原因。', tone: 'error' },
        { id: 'failure-record', text: '2. 保存失败原因供入口层显示。', tone: 'error' },
      ],
    },
  ],
  calls: [
    {
      id: 'call-run-validate',
      sourceMethodId: 'task-run-feature',
      sourceStepId: 'run-validate',
      targetMethodId: 'service-validate-request',
      kind: 'certain',
      targetSide: 'right',
      lane: -1,
      label: '校验业务输入',
    },
    {
      id: 'call-run-load',
      sourceMethodId: 'task-run-feature',
      sourceStepId: 'run-load',
      targetMethodId: 'service-load-data',
      kind: 'certain',
      targetSide: 'right',
      lane: 0,
      label: '读取待处理数据',
    },
    {
      id: 'call-load-normalize',
      sourceMethodId: 'service-load-data',
      sourceStepId: 'load-normalize',
      targetMethodId: 'service-normalize-records',
      kind: 'certain',
      targetSide: 'right',
      lane: -1,
      label: '统一记录格式',
    },
    {
      id: 'call-run-save',
      sourceMethodId: 'task-run-feature',
      sourceStepId: 'run-save',
      targetMethodId: 'storage-save-result',
      kind: 'conditional',
      targetSide: 'left',
      lane: -1,
      label: '满足保存条件时写入结果',
    },
    {
      id: 'call-run-failure',
      sourceMethodId: 'task-run-feature',
      sourceStepId: 'run-error',
      targetMethodId: 'storage-report-failure',
      kind: 'conditional',
      targetSide: 'left',
      lane: 0,
      label: '执行异常时记录失败信息',
    },
  ],
};
