export const panoramaData = {
  directories: [
    {
      id: 'dir-src',
      name: 'src',
      description: '当前项目的业务源码根目录。',
      parentId: null,
    },
    {
      id: 'dir-tools',
      name: 'tools',
      description: '命令行入口：读取参数、组织一次完整运行并输出结果。',
      parentId: 'dir-src',
    },
    {
      id: 'dir-tasks',
      name: 'tasks',
      description: '任务编排层：组织全景拍摄、帧采集和图像拼接流程。',
      parentId: 'dir-src',
    },
    {
      id: 'dir-hardware',
      name: 'hardware',
      description: '硬件边界：封装摄像头会话和舵机 GPIO 操作。',
      parentId: 'dir-src',
    },
  ],
  files: [
    {
      id: 'file-tool-capture-panorama',
      directoryId: 'dir-tools',
      name: 'capture_panorama.py',
      path: 'src/tools/capture_panorama.py',
      description: '全景功能的命令行运行入口，负责参数、错误提示和最终拼接选择。',
    },
    {
      id: 'file-task-panorama',
      directoryId: 'dir-tasks',
      name: 'panorama.py',
      path: 'src/tasks/panorama.py',
      description: '全景功能核心：计算角度、逐帧拍摄、释放舵机并按需拼接。',
    },
    {
      id: 'file-hardware-camera',
      directoryId: 'dir-hardware',
      name: 'camera.py',
      path: 'src/hardware/camera.py',
      description: '摄像头硬件边界，提供长连接 OpenCV 会话和单次拍照入口。',
    },
    {
      id: 'file-hardware-servo',
      directoryId: 'dir-hardware',
      name: 'servo.py',
      path: 'src/hardware/servo.py',
      description: '舵机硬件边界，负责 PWM 初始化、转动和自身 GPIO 清理。',
    },
  ],
  methods: [
    {
      id: 'tool-parse-args',
      fileId: 'file-tool-capture-panorama',
      signature: 'parse_args() -> argparse.Namespace',
      meaning: '定义并读取一次全景拍摄需要的命令行参数。',
      inputs: [],
      inputNote: '没有显式参数。它直接读取启动程序时写在命令行中的选项，例如 --backend opencv 和 --frames 5。',
      output: {
        summary: '返回 argparse.Namespace。它像一个参数收纳盒，下面每个字段对应一个命令行选项。',
        fields: [
          { name: 'backend', summary: '摄像头后端：auto、opencv、libcamera 或 raspistill。', detail: '“后端”是程序实际调用摄像头的方式。opencv 常用于 USB 摄像头；libcamera 和 raspistill 常用于不同版本树莓派系统的 CSI 摄像头；auto 会按代码顺序逐个尝试。' },
          { name: 'device', summary: 'OpenCV 摄像头设备编号，默认 0。', detail: '一台机器可能连接多个摄像头，OpenCV 通常用 0、1、2 区分；libcamera 和 raspistill 分支不使用此值。' },
          { name: 'output_dir', summary: '所有全景拍摄会话的父目录。', detail: '例如 captures/panoramas。每运行一次任务，还会在这个目录下面创建一个独立的会话目录，避免不同批次的照片混在一起。' },
          { name: 'session_name', summary: '可选的本次会话目录名称；不填写时使用时间生成。', detail: '“会话”就是一次完整的全景拍摄运行。同一次运行产生的原始照片和全景图会放在同一个独立目录中。' },
          { name: 'frames', summary: '本次要拍摄的原始照片数量。' },
          { name: 'start_angle', summary: '水平舵机开始拍摄的角度，范围 0～180 度。' },
          { name: 'end_angle', summary: '水平舵机结束拍摄的角度，范围 0～180 度。' },
          { name: 'pan_pin', summary: '水平舵机使用的 BCM GPIO 引脚；可设为 none。', detail: 'BCM 是树莓派 GPIO 的一种编号方式。这里必须使用项目配置确认的 BCM 编号，不能混用物理针脚号或 wiringPi 编号。' },
          { name: 'tilt_pin', summary: '可选的垂直舵机 BCM GPIO 引脚。' },
          { name: 'tilt_angle', summary: '拍摄前垂直舵机要固定到的角度。' },
          { name: 'no_servo', summary: '是否禁用舵机；为 true 时从当前方向连续拍照。' },
          { name: 'width', summary: '请求的照片宽度，单位为像素。' },
          { name: 'height', summary: '请求的照片高度，单位为像素。' },
          { name: 'warmup_frames', summary: '正式保存前先丢弃的预热帧数量。', detail: '摄像头刚打开或刚调整方向时，前几帧可能曝光、白平衡或画面稳定性较差。丢弃这些帧后再保存，通常能得到更稳定的照片。' },
          { name: 'warmup_seconds', summary: '打开摄像头后等待稳定的秒数。' },
          { name: 'servo_settle_seconds', summary: '每次舵机转动后等待到位的秒数。' },
          { name: 'capture_delay_seconds', summary: '每个角度读图前额外等待的秒数。' },
          { name: 'fps', summary: '请求的摄像头帧率；不填写则使用设备默认值。' },
          { name: 'fourcc', summary: '请求的视频像素格式，例如 MJPG。', detail: 'FOURCC 是由四个字符表示的视频编码或像素格式标识。摄像头和驱动不支持时，请求值可能不会生效。' },
          { name: 'brightness', summary: '可选的摄像头亮度设置。' },
          { name: 'contrast', summary: '可选的摄像头对比度设置。' },
          { name: 'saturation', summary: '可选的摄像头饱和度设置。' },
          { name: 'gain', summary: '可选的摄像头增益设置。', detail: '增益会放大传感器信号；提高增益可能让画面变亮，也可能同时放大噪点。' },
          { name: 'exposure', summary: '可选的摄像头曝光设置。' },
          { name: 'focus', summary: '可选的手动焦距设置。' },
          { name: 'sharpness', summary: '可选的摄像头内部锐化强度。' },
          { name: 'autofocus', summary: '自动对焦控制：on、off 或 keep。' },
          { name: 'auto_exposure', summary: '传给 OpenCV/V4L2 的自动曝光原始值。', detail: '不同摄像头驱动的取值可能不同；许多 V4L2 设备用 1 表示手动曝光、3 表示自动曝光，最终是否生效由硬件和驱动决定。' },
          { name: 'burst_count', summary: '每个角度拍摄的候选帧数量，最终保存最清晰的一帧。', detail: '“候选帧”是同一角度连续读取的多张临时图像。数量大于 1 时，程序计算清晰度分数，只把分数最高的一张写入文件。' },
          { name: 'no_stitch', summary: '是否只保存原始照片并跳过全景拼接。' },
          { name: 'stitch_confidence', summary: 'OpenCV 拼接器接受图像匹配的置信阈值。', detail: '置信阈值用于过滤可信度较低的图像匹配。数值过高可能导致照片无法连接，过低则可能接受错误匹配；当前默认值是项目代码实际使用的 0.01。' },
        ],
      },
      source: {
        path: 'src/tools/capture_panorama.py',
        startLine: 49,
        endLine: 191,
      },
      defaultExpanded: false,
      compact: false,
      steps: [
        {
          id: 'parse-create-parser',
          text: '1. 创建参数解析器，并说明本工具用于拍摄原始照片和可选拼接。',
          tone: 'normal',
        },
        {
          id: 'parse-register-options',
          text: '2. 注册摄像头后端、设备、输出目录、角度、帧数、舵机、图像质量和拼接参数；--no-servo、--no-stitch 使用布尔开关，可选引脚和角度交给本文件的解析回调处理。',
          tone: 'normal',
        },
        {
          id: 'parse-return',
          text: '3. 解析当前进程参数并返回 Namespace。',
          tone: 'normal',
        },
        {
          id: 'parse-invalid',
          text: '4. 参数格式或 choices 不合法时，由 argparse 直接终止并输出具体提示。',
          tone: 'error',
        },
      ],
    },
    {
      id: 'tool-build-camera-settings',
      fileId: 'file-tool-capture-panorama',
      signature: 'build_camera_settings(args) -> OpenCVCameraSettings',
      meaning: '把命令行中的图像控制项整理为摄像头配置对象。',
      inputs: [
        { name: 'args', summary: 'parse_args() 返回的命令行参数收纳对象。', detail: '本方法只读取其中与 OpenCV 图像控制有关的字段，不会修改原参数对象。' },
      ],
      output: {
        summary: '返回 OpenCVCameraSettings，把可选的 OpenCV 摄像头控制集中到一个对象中。',
        fields: [
          { name: 'fps', summary: '请求的帧率。' },
          { name: 'fourcc', summary: '请求的像素或视频格式。' },
          { name: 'brightness', summary: '亮度。' },
          { name: 'contrast', summary: '对比度。' },
          { name: 'saturation', summary: '饱和度。' },
          { name: 'gain', summary: '传感器信号增益。' },
          { name: 'exposure', summary: '曝光值。' },
          { name: 'focus', summary: '手动焦距。' },
          { name: 'sharpness', summary: '摄像头内部锐化强度。' },
          { name: 'autofocus', summary: 'true 表示打开自动对焦，false 表示关闭，None 表示保持设备现状。' },
          { name: 'auto_exposure', summary: '驱动使用的自动曝光原始值。' },
          { name: 'buffer_size', summary: 'OpenCV 请求保留的缓冲帧数量，当前固定为 1。', detail: '较小的缓冲区可减少读到舵机转动前旧画面的概率，但是否完全生效取决于摄像头驱动。' },
        ],
      },
      source: {
        path: 'src/tools/capture_panorama.py',
        startLine: 194,
        endLine: 215,
      },
      defaultExpanded: false,
      compact: true,
      steps: [
        {
          id: 'settings-autofocus',
          text: '1. 将 autofocus 的 on、off、keep 分别转换为 True、False、None。',
          tone: 'condition',
        },
        {
          id: 'settings-build',
          text: '2. 汇总帧率、格式、亮度、曝光、焦距等参数，构造并返回 OpenCVCameraSettings。',
          tone: 'normal',
        },
      ],
    },
    {
      id: 'tool-main',
      fileId: 'file-tool-capture-panorama',
      signature: 'main() -> int',
      meaning: '命令行总入口：先拍原始帧，再根据 --no-stitch 决定是否单独拼接。',
      inputs: [],
      inputNote: '没有显式参数。它通过 parse_args() 读取进程命令行，并把这些值传给全景任务。',
      output: {
        summary: '返回整数退出码：0 表示拍摄和可选拼接成功，1 表示过程中出现可报告的失败。',
      },
      source: {
        path: 'src/tools/capture_panorama.py',
        startLine: 218,
        endLine: 293,
      },
      defaultExpanded: false,
      compact: false,
      steps: [
        {
          id: 'main-parse',
          text: '1. 调用 parse_args() 取得本次运行参数。',
          tone: 'normal',
        },
        {
          id: 'main-summary',
          text: '2. 打印项目根目录、摄像头后端、设备、拍摄角度和舵机启用状态，便于实机核对。',
          tone: 'condition',
        },
        {
          id: 'main-settings',
          text: '3. 调用 build_camera_settings()，把命令行图像参数整理成摄像头配置。',
          tone: 'normal',
        },
        {
          id: 'main-capture',
          text: '4. 调用 capture_panorama() 拍摄原始帧；这里明确传入 stitch=False，所以核心任务此时不会拼接。',
          tone: 'normal',
        },
        {
          id: 'main-capture-error',
          text: '5. 如果摄像头、全景、舵机或参数校验失败，打印错误和最小排查提示并返回 1。',
          tone: 'error',
        },
        {
          id: 'main-skip',
          text: '6. 打印原始帧数量和会话目录；若指定 --no-stitch，则保留原图、跳过拼接并返回 0。',
          tone: 'condition',
        },
        {
          id: 'main-stitch',
          text: '7. 未指定 --no-stitch 时，调用 stitch_images() 把刚拍摄的帧拼成 panorama.jpg。',
          tone: 'condition',
        },
        {
          id: 'main-stitch-error',
          text: '8. 拼接失败时报告错误和保留原始帧的位置，并返回 1。',
          tone: 'error',
        },
        {
          id: 'main-success',
          text: '9. 拼接成功时打印全景图路径和完成消息，并返回 0。',
          tone: 'normal',
        },
      ],
    },
    {
      id: 'task-build-angle-sequence',
      fileId: 'file-task-panorama',
      signature: 'build_angle_sequence(start_angle, end_angle, frame_count) -> Tuple[float, ...]',
      meaning: '计算从起始角到终止角的等间距拍摄角度。',
      inputs: [
        { name: 'start_angle', summary: '第一张照片对应的水平舵机角度，范围 0～180 度。' },
        { name: 'end_angle', summary: '最后一张照片对应的水平舵机角度，范围 0～180 度。' },
        { name: 'frame_count', summary: '要生成多少个拍摄角度，也就是计划拍多少张原始照片。' },
      ],
      output: {
        summary: '返回不可变的角度元组，顺序就是后续实际拍摄顺序。',
        fields: [
          { name: '每一项', summary: '一个浮点角度值；首项等于 start_angle，末项等于 end_angle，中间项等间距分布。' },
        ],
      },
      source: {
        path: 'src/tasks/panorama.py',
        startLine: 44,
        endLine: 69,
      },
      defaultExpanded: false,
      compact: false,
      steps: [
        {
          id: 'angles-count',
          text: '1. 检查 frame_count 至少为 1，否则立即抛出 ValueError。',
          tone: 'error',
        },
        {
          id: 'angles-validate',
          text: '2. 调用 _validate_angle() 分别校验起始角和终止角是否在舵机允许范围内。',
          tone: 'normal',
        },
        {
          id: 'angles-single',
          text: '3. 如果只拍一张，直接返回起始角，避免除以 frame_count - 1。',
          tone: 'condition',
        },
        {
          id: 'angles-build',
          text: '4. 计算相邻角度步长，按索引生成并四舍五入全部角度；允许从大角度反向扫到小角度。',
          tone: 'loop',
        },
      ],
    },
    {
      id: 'task-build-session-dir',
      fileId: 'file-task-panorama',
      signature: 'build_session_dir(output_dir=DEFAULT_PANORAMA_DIR, *, session_name=None) -> Path',
      meaning: '确定本次全景拍摄独立保存目录的路径。',
      inputs: [
        { name: 'output_dir', summary: '保存全部全景会话的父目录。', detail: '例如 captures/panoramas。它不是本次拍摄的最终目录，而是多个拍摄批次共同所在的上级目录。' },
        { name: 'session_name', summary: '可选的本次会话名称；不填写时根据当前时间生成。', detail: '一次“会话”代表一次完整的全景拍摄运行，例如 panorama_20260710_143000。原始帧和最终全景图都会归档在这个独立目录中。' },
      ],
      output: {
        summary: '返回本次会话目录的 Path 路径对象；这里只计算路径，还没有创建文件夹。',
        fields: [
          { name: '会话目录', summary: '一次全景拍摄专属的文件夹，用来隔离本轮原始照片和最终全景图。', detail: '例如 captures/panoramas/panorama_20260710_143000。这样连续运行多次时，不会覆盖上一轮产生的照片。' },
        ],
      },
      source: {
        path: 'src/tasks/panorama.py',
        startLine: 72,
        endLine: 88,
      },
      defaultExpanded: false,
      compact: true,
      steps: [
        {
          id: 'session-name',
          text: '1. 优先使用传入的 session_name；未传时按当前时间生成 panorama_年月日_时分秒。',
          tone: 'condition',
        },
        {
          id: 'session-path',
          text: '2. 将目录名拼到 output_dir 下并返回 Path。',
          tone: 'normal',
        },
      ],
    },
    {
      id: 'task-capture-panorama',
      fileId: 'file-task-panorama',
      signature: 'capture_panorama(*, output_dir, session_name, backend, device_index, width, height, warmup_frames, warmup_seconds, start_angle, end_angle, frame_count, pan_servo_pin, tilt_servo_pin, tilt_angle, use_servo, servo_settle_seconds, capture_delay_seconds, camera_settings, burst_count, stitch, stitch_confidence) -> PanoramaResult',
      meaning: '核心业务入口：准备会话、管理舵机、拍摄全套原始帧并可选生成全景图。',
      inputs: [
        { name: 'output_dir', summary: '保存全部全景会话的父目录。', detail: '本次运行还会在它下面建立独立的会话目录。' },
        { name: 'session_name', summary: '可选的本次会话目录名称；None 表示根据时间自动生成。' },
        { name: 'backend', summary: '摄像头后端：auto、opencv、libcamera 或 raspistill。', detail: '后端决定程序通过哪套接口访问摄像头。OpenCV 分支会复用一个长连接会话；其他分支逐张调用 capture_photo()。' },
        { name: 'device_index', summary: 'OpenCV 摄像头设备编号，通常为 0 或 1。' },
        { name: 'width', summary: '请求的照片宽度，单位为像素；None 表示不主动设置。' },
        { name: 'height', summary: '请求的照片高度，单位为像素；None 表示不主动设置。' },
        { name: 'warmup_frames', summary: '正式保存前要丢弃的预热帧数量。', detail: '用于避开摄像头刚打开时曝光和画面尚未稳定的帧。' },
        { name: 'warmup_seconds', summary: '摄像头打开后等待稳定的秒数。' },
        { name: 'start_angle', summary: '水平舵机的起始拍摄角度，范围 0～180 度。' },
        { name: 'end_angle', summary: '水平舵机的结束拍摄角度，范围 0～180 度。' },
        { name: 'frame_count', summary: '计划拍摄的原始照片数量。' },
        { name: 'pan_servo_pin', summary: '水平舵机的 BCM GPIO 引脚；不用舵机时可为 None。', detail: 'BCM 是树莓派 GPIO 编号体系。本参数必须与实际接线和项目硬件配置一致。' },
        { name: 'tilt_servo_pin', summary: '可选的垂直舵机 BCM GPIO 引脚。' },
        { name: 'tilt_angle', summary: '可选的固定俯仰角度，拍摄前由垂直舵机转到该位置。' },
        { name: 'use_servo', summary: '是否让任务创建并移动舵机。' },
        { name: 'servo_settle_seconds', summary: '舵机收到角度命令后等待到位的秒数。' },
        { name: 'capture_delay_seconds', summary: '每次读图前额外等待的秒数，减少转动余振影响。' },
        { name: 'camera_settings', summary: '可选的 OpenCVCameraSettings 图像控制对象。', detail: '其中可以携带帧率、曝光、对焦、亮度等请求值；硬件或驱动不支持的项目可能不会生效。' },
        { name: 'burst_count', summary: '每个角度读取的候选帧数量，最终保留最清晰的一帧。', detail: '大于 1 时会比较多张候选帧的清晰度；值越大耗时越长。' },
        { name: 'stitch', summary: '是否在本方法内部继续执行全景拼接。', detail: 'CLI 的 main() 明确传入 false，先完成原始帧拍摄，再由外层根据 --no-stitch 决定是否拼接。' },
        { name: 'stitch_confidence', summary: '传给 OpenCV 拼接器的图像匹配置信阈值。', detail: '阈值过高可能拒绝可用匹配，过低可能接受错误匹配；只有 stitch 为 true 时在本方法内使用。' },
      ],
      output: {
        summary: '返回 PanoramaResult，集中描述本次全景拍摄产生了什么以及保存在哪里。',
        fields: [
          { name: 'session_dir', summary: '本次拍摄独占的会话目录。', detail: '一次完整运行产生的 frames 原始照片目录和可选 panorama.jpg 都位于这里，避免与其他运行批次混在一起。' },
          { name: 'frame_paths', summary: '所有成功保存的原始照片路径，顺序与拍摄角度一致。', detail: '它是不可变元组。第 1 个路径对应 angles 的第 1 个角度，以此类推。' },
          { name: 'panorama_path', summary: '拼接后的 panorama.jpg 路径；没有执行拼接时为 None。' },
          { name: 'angles', summary: '本次实际采用的水平拍摄角度序列。' },
        ],
      },
      source: {
        path: 'src/tasks/panorama.py',
        startLine: 91,
        endLine: 215,
      },
      defaultExpanded: true,
      compact: false,
      steps: [
        {
          id: 'capture-validate',
          text: '1. 校验摄像头后端、等待时间、预热帧数和 burst_count；若配置了垂直角度，再调用 _validate_angle() 校验其范围。任何无效参数都会在接触硬件前报错。',
          tone: 'error',
        },
        {
          id: 'capture-angles',
          text: '2. 调用 build_angle_sequence() 生成水平舵机的等间距拍摄角度。',
          tone: 'normal',
        },
        {
          id: 'capture-session',
          text: '3. 调用 build_session_dir() 得到会话目录，并创建其中的 frames 原始照片目录。',
          tone: 'normal',
        },
        {
          id: 'capture-servo-init',
          text: '4. 进入受保护的硬件阶段；use_servo 为真时要求水平引脚存在并创建水平舵机，垂直引脚和角度同时存在时再创建垂直舵机。',
          tone: 'condition',
        },
        {
          id: 'capture-tilt',
          text: '5. 如果垂直舵机已创建，调用 move_to() 将镜头固定到目标俯仰角。',
          tone: 'condition',
        },
        {
          id: 'capture-frames',
          text: '6. 调用 _capture_frames()，传入角度、舵机和摄像头参数，取得全部原始照片路径。',
          tone: 'normal',
        },
        {
          id: 'capture-cleanup',
          text: '7. 无论舵机初始化或拍摄是否异常，finally 都会关闭已成功创建的垂直、水平舵机，停止 PWM 并释放各自 GPIO。',
          tone: 'finally',
        },
        {
          id: 'capture-stitch',
          text: '8. stitch 为真时调用 stitch_images() 生成 panorama.jpg；CLI 主入口传入 False，因此主工具会在外层另行决定是否拼接。',
          tone: 'condition',
        },
        {
          id: 'capture-result',
          text: '9. 汇总会话目录、不可变的原始帧路径、可选全景图路径和拍摄角度，返回 PanoramaResult。',
          tone: 'normal',
        },
      ],
    },
    {
      id: 'task-stitch-images',
      fileId: 'file-task-panorama',
      signature: 'stitch_images(image_paths, output_path, *, confidence_threshold=0.01) -> Path',
      meaning: '读取多张原始照片并使用 OpenCV Stitcher 输出一张全景图。',
      inputs: [
        { name: 'image_paths', summary: '按拍摄顺序排列的原始照片路径。', detail: '至少需要两张可读取的照片；相邻照片应包含足够重叠区域，否则 OpenCV 可能找不到共同特征。' },
        { name: 'output_path', summary: '拼接成功后全景图要写入的准确文件路径。' },
        { name: 'confidence_threshold', summary: 'OpenCV 接受图像匹配的置信阈值，默认 0.01。', detail: '拼接器会寻找不同照片中的共同特征。此阈值决定多低的匹配可信度仍可参与拼接。' },
      ],
      output: {
        summary: '返回成功写入的全景图 Path 路径对象；读取、拼接或写入失败时抛出 PanoramaError。',
      },
      source: {
        path: 'src/tasks/panorama.py',
        startLine: 218,
        endLine: 264,
      },
      defaultExpanded: false,
      compact: false,
      steps: [
        {
          id: 'stitch-count',
          text: '1. 要求至少两张原图，否则抛出 PanoramaError。',
          tone: 'error',
        },
        {
          id: 'stitch-import',
          text: '2. 动态导入 cv2；环境没有 OpenCV 时转换为清晰的 PanoramaError。',
          tone: 'error',
        },
        {
          id: 'stitch-read',
          text: '3. 按给定顺序循环读取每个文件；任意图片无法读取就立即报出具体路径。',
          tone: 'loop',
        },
        {
          id: 'stitch-create',
          text: '4. 调用 _create_stitcher() 创建与当前 OpenCV 版本兼容的拼接器。',
          tone: 'normal',
        },
        {
          id: 'stitch-confidence',
          text: '5. 如果拼接器提供置信阈值接口，就设置 confidence_threshold。',
          tone: 'condition',
        },
        {
          id: 'stitch-run',
          text: '6. 执行拼接并检查状态和结果图；失败时调用 _format_stitch_error() 把状态码转换为可行动的提示。',
          tone: 'error',
        },
        {
          id: 'stitch-write',
          text: '7. 创建目标父目录并写入全景图；写入失败时抛出 PanoramaError。',
          tone: 'error',
        },
        {
          id: 'stitch-return',
          text: '8. 返回成功写入的目标路径。',
          tone: 'normal',
        },
      ],
    },
    {
      id: 'task-capture-frames',
      fileId: 'file-task-panorama',
      signature: '_capture_frames(*, frames_dir, angles, pan_servo, backend, device_index, width, height, warmup_frames, warmup_seconds, capture_delay_seconds, camera_settings, burst_count) -> Tuple[Path, ...]',
      meaning: '根据后端选择长连接或逐张打开摄像头的拍摄策略。',
      inputs: [
        { name: 'frames_dir', summary: '本次会话中专门保存原始照片的 frames 目录。' },
        { name: 'angles', summary: '按拍摄顺序排列的水平舵机角度序列。' },
        { name: 'pan_servo', summary: '可选的水平 ServoController；None 表示不移动舵机。' },
        { name: 'backend', summary: '摄像头后端；opencv 使用长会话，其他值逐张拍照。', detail: '后端决定走 _capture_frames_with_opencv_session() 还是 capture_photo()。' },
        { name: 'device_index', summary: 'OpenCV 摄像头设备编号。' },
        { name: 'width', summary: '请求的照片宽度，单位为像素。' },
        { name: 'height', summary: '请求的照片高度，单位为像素。' },
        { name: 'warmup_frames', summary: '正式保存前丢弃的预热帧数。' },
        { name: 'warmup_seconds', summary: '打开摄像头后等待稳定的秒数。' },
        { name: 'capture_delay_seconds', summary: '舵机到位后、读取照片前额外等待的秒数。' },
        { name: 'camera_settings', summary: '可选的 OpenCV 图像控制对象。' },
        { name: 'burst_count', summary: '每个角度参与清晰度比较的候选帧数量。' },
      ],
      output: {
        summary: '返回全部成功保存的原始照片 Path 元组，顺序与 angles 一一对应。',
        fields: [
          { name: '每一项', summary: '一张原始照片的准确文件路径，例如 frames/frame_00_angle_020.jpg。' },
        ],
      },
      source: {
        path: 'src/tasks/panorama.py',
        startLine: 267,
        endLine: 319,
      },
      defaultExpanded: false,
      compact: false,
      steps: [
        {
          id: 'frames-backend',
          text: '1. backend 等于 opencv 时，调用 _capture_frames_with_opencv_session()，整个角度序列共用一个摄像头会话并直接返回。',
          tone: 'condition',
        },
        {
          id: 'frames-init',
          text: '2. 其他后端创建空的 frame_paths，准备逐角度调用单次拍照入口。',
          tone: 'normal',
        },
        {
          id: 'frames-loop',
          text: '3. 按 angles 的顺序循环，同时取得照片索引和当前角度。',
          tone: 'loop',
        },
        {
          id: 'frames-move',
          text: '4. 如果水平舵机存在，调用 move_to() 转到当前角度。',
          tone: 'condition',
        },
        {
          id: 'frames-delay',
          text: '5. capture_delay_seconds 大于 0 时额外等待，减少舵机运动造成的模糊。',
          tone: 'condition',
        },
        {
          id: 'frames-path',
          text: '6. 调用 _frame_path() 生成包含索引和角度的唯一照片路径。',
          tone: 'normal',
        },
        {
          id: 'frames-capture',
          text: '7. 调用 capture_photo() 使用 auto、libcamera 或 raspistill 后端拍照，并把成功路径加入列表。',
          tone: 'condition',
        },
        {
          id: 'frames-return',
          text: '8. 循环结束后把路径列表转换为元组返回。',
          tone: 'normal',
        },
      ],
    },
    {
      id: 'task-capture-frames-opencv',
      fileId: 'file-task-panorama',
      signature: '_capture_frames_with_opencv_session(*, frames_dir, angles, pan_servo, device_index, width, height, warmup_frames, warmup_seconds, capture_delay_seconds, camera_settings, burst_count) -> Tuple[Path, ...]',
      meaning: '在一个持续打开的 OpenCV 会话中完成全部角度的拍摄。',
      inputs: [
        { name: 'frames_dir', summary: '保存本次全部原始照片的 frames 目录。' },
        { name: 'angles', summary: '按拍摄顺序排列的水平角度序列。' },
        { name: 'pan_servo', summary: '可选的水平 ServoController；None 表示镜头保持当前方向。' },
        { name: 'device_index', summary: '要持续打开的 OpenCV 摄像头设备编号。' },
        { name: 'width', summary: '请求的照片宽度，单位为像素。' },
        { name: 'height', summary: '请求的照片高度，单位为像素。' },
        { name: 'warmup_frames', summary: '会话刚打开时要丢弃的预热帧数。' },
        { name: 'warmup_seconds', summary: '会话刚打开时等待曝光稳定的秒数。' },
        { name: 'capture_delay_seconds', summary: '每次移动舵机后、保存照片前等待的秒数。' },
        { name: 'camera_settings', summary: '应用到持续 OpenCV 会话的图像控制对象。' },
        { name: 'burst_count', summary: '每个角度读取并比较的候选帧数量。', detail: '程序对候选帧计算清晰度分数，只保存分数最高的一张。' },
      ],
      output: {
        summary: '返回持续会话中保存的全部原始照片路径元组，顺序与 angles 一致。',
      },
      source: {
        path: 'src/tasks/panorama.py',
        startLine: 322,
        endLine: 358,
      },
      defaultExpanded: false,
      compact: false,
      steps: [
        {
          id: 'opencv-init-paths',
          text: '1. 创建空的 frame_paths，用于保持照片与角度的顺序对应。',
          tone: 'normal',
        },
        {
          id: 'opencv-session-open',
          text: '2. 构造 OpenCVCameraSession，并通过 with 隐式调用 __enter__() 打开、配置和预热摄像头。',
          tone: 'normal',
        },
        {
          id: 'opencv-loop',
          text: '3. 在同一个已打开的摄像头会话内，按顺序循环索引和角度。',
          tone: 'loop',
        },
        {
          id: 'opencv-move',
          text: '4. 如果水平舵机存在，调用 move_to() 转到当前角度。',
          tone: 'condition',
        },
        {
          id: 'opencv-path',
          text: '5. 调用 _frame_path() 生成当前角度的目标照片路径。',
          tone: 'normal',
        },
        {
          id: 'opencv-capture',
          text: '6. 调用会话 capture()；把舵机后的额外延时交给摄像头层，并从候选帧中保存最清晰的一张。',
          tone: 'loop',
        },
        {
          id: 'opencv-append',
          text: '7. 保存成功后把路径加入列表。',
          tone: 'normal',
        },
        {
          id: 'opencv-session-close',
          text: '8. 离开 with 时隐式调用 __exit__()；即使循环或拍照抛出异常，也会释放 OpenCV 摄像头。',
          tone: 'finally',
        },
        {
          id: 'opencv-return',
          text: '9. 正常完成后把路径列表转换为元组返回。',
          tone: 'normal',
        },
      ],
    },
    {
      id: 'task-create-stitcher',
      fileId: 'file-task-panorama',
      signature: '_create_stitcher(cv2)',
      meaning: '兼容不同 OpenCV 版本的 Stitcher 创建接口。',
      inputs: [
        { name: 'cv2', summary: '已经成功导入的 OpenCV Python 模块。', detail: '不同 OpenCV 版本创建 Stitcher 的 API 名称不同，本方法通过检查 cv2 上实际存在的接口进行兼容选择。' },
      ],
      output: {
        summary: '返回可用的 OpenCV Stitcher 拼接器对象；当前 OpenCV 没有兼容接口时抛出 PanoramaError。',
      },
      source: {
        path: 'src/tasks/panorama.py',
        startLine: 361,
        endLine: 370,
      },
      defaultExpanded: false,
      compact: true,
      steps: [
        {
          id: 'create-stitcher-current',
          text: '1. 优先使用当前接口 Stitcher_create；若 PANORAMA 模式常量存在则显式传入。',
          tone: 'condition',
        },
        {
          id: 'create-stitcher-legacy',
          text: '2. 当前接口不存在时尝试旧接口 createStitcher(False)；两者都没有则报错。',
          tone: 'error',
        },
      ],
    },
    {
      id: 'task-frame-path',
      fileId: 'file-task-panorama',
      signature: '_frame_path(frames_dir, index, angle) -> Path',
      meaning: '为单张原始帧生成包含顺序和角度的文件名。',
      inputs: [
        { name: 'frames_dir', summary: '原始照片所在的 frames 目录。' },
        { name: 'index', summary: '当前照片在本轮拍摄中的序号，从 0 开始。' },
        { name: 'angle', summary: '拍摄当前照片时使用的水平角度。' },
      ],
      output: {
        summary: '返回当前照片的 Path，例如 frames/frame_00_angle_020.jpg；本方法只生成路径，不写文件。',
      },
      source: {
        path: 'src/tasks/panorama.py',
        startLine: 373,
        endLine: 374,
      },
      defaultExpanded: false,
      compact: true,
      steps: [
        {
          id: 'frame-path-build',
          text: '1. 调用 _format_angle() 取得文件名安全的角度文本，再与两位索引和 frames_dir 拼成 jpg 路径。',
          tone: 'normal',
        },
      ],
    },
    {
      id: 'task-format-angle',
      fileId: 'file-task-panorama',
      signature: '_format_angle(angle) -> str',
      meaning: '把角度转换为稳定且可用于文件名的文本。',
      inputs: [
        { name: 'angle', summary: '要放入文件名的角度值。' },
      ],
      output: {
        summary: '返回适合文件名使用的角度字符串：整数补成三位，小数点改成 p，负号改成 m。',
      },
      source: {
        path: 'src/tasks/panorama.py',
        startLine: 377,
        endLine: 380,
      },
      defaultExpanded: false,
      compact: true,
      steps: [
        {
          id: 'format-angle-integer',
          text: '1. 如果角度是整数，转为至少三位的零填充文本。',
          tone: 'condition',
        },
        {
          id: 'format-angle-decimal',
          text: '2. 否则保留三位小数，并把小数点和负号替换为文件名字符。',
          tone: 'normal',
        },
      ],
    },
    {
      id: 'task-validate-angle',
      fileId: 'file-task-panorama',
      signature: '_validate_angle(name, angle) -> None',
      meaning: '统一校验舵机角度是否位于 0～180 度。',
      inputs: [
        { name: 'name', summary: '要显示在错误消息中的参数名称。' },
        { name: 'angle', summary: '待检查的角度值，合法范围为 0～180 度。' },
      ],
      output: {
        summary: '没有返回数据；角度超出 0～180 度时立即抛出 ValueError。',
      },
      source: {
        path: 'src/tasks/panorama.py',
        startLine: 383,
        endLine: 386,
      },
      defaultExpanded: false,
      compact: true,
      steps: [
        {
          id: 'validate-angle-range',
          text: '1. 将角度转成 float；小于 0 或大于 180 时，用传入的参数名抛出 ValueError。',
          tone: 'error',
        },
      ],
    },
    {
      id: 'task-format-stitch-error',
      fileId: 'file-task-panorama',
      signature: '_format_stitch_error(status) -> str',
      meaning: '把 OpenCV 拼接状态码翻译成便于排查的失败提示。',
      inputs: [
        { name: 'status', summary: 'OpenCV Stitcher 返回的整数失败状态码。', detail: '状态码只能说明拼接器在哪一类阶段失败，不能单独证明具体照片问题，因此返回文本同时给出常见原因和排查建议。' },
      ],
      output: {
        summary: '返回一段错误说明文本，包含状态码、常见原因以及可尝试的调整方向。',
      },
      source: {
        path: 'src/tasks/panorama.py',
        startLine: 389,
        endLine: 396,
      },
      defaultExpanded: false,
      compact: true,
      steps: [
        {
          id: 'format-stitch-lookup',
          text: '1. 按状态码 1、2、3 选择特征不足、单应估计失败或相机参数调整失败提示；未知状态使用通用说明。',
          tone: 'condition',
        },
        {
          id: 'format-stitch-return',
          text: '2. 将状态码和提示合并为最终错误文本。',
          tone: 'normal',
        },
      ],
    },
    {
      id: 'camera-session-init',
      fileId: 'file-hardware-camera',
      signature: 'OpenCVCameraSession.__init__(*, device_index=0, width=None, height=None, warmup_frames=5, warmup_seconds=0.5, settings=None)',
      meaning: '保存长连接摄像头会话配置，但此时还没有打开设备。',
      inputs: [
        { name: 'device_index', summary: 'OpenCV 摄像头设备编号，默认 0。' },
        { name: 'width', summary: '可选的请求画面宽度；None 表示保持设备默认值。' },
        { name: 'height', summary: '可选的请求画面高度；None 表示保持设备默认值。' },
        { name: 'warmup_frames', summary: '会话打开后要先读取并丢弃的预热帧数量。', detail: '预热帧不会写入文件，用于等待曝光、白平衡和摄像头缓存趋于稳定。' },
        { name: 'warmup_seconds', summary: '设备打开后额外等待稳定的秒数。' },
        { name: 'settings', summary: '可选的 OpenCVCameraSettings 图像控制对象。' },
      ],
      output: {
        summary: '__init__() 本身没有返回数据；OpenCVCameraSession(...) 构造表达式会得到保存了这些配置的新会话实例，但此时摄像头尚未打开。',
      },
      source: {
        path: 'src/hardware/camera.py',
        startLine: 91,
        endLine: 113,
      },
      defaultExpanded: false,
      compact: false,
      steps: [
        {
          id: 'camera-init-validate',
          text: '1. 拒绝负数 warmup_frames 和 warmup_seconds，避免把无效预热配置带到硬件阶段。',
          tone: 'error',
        },
        {
          id: 'camera-init-store',
          text: '2. 保存设备、尺寸和预热配置；未传 settings 时创建默认配置，并把 cv2 与摄像头句柄初始化为 None。',
          tone: 'normal',
        },
      ],
    },
    {
      id: 'camera-session-open',
      fileId: 'file-hardware-camera',
      signature: 'OpenCVCameraSession.open() -> OpenCVCameraSession',
      meaning: '真正打开、配置并预热 OpenCV 摄像头设备。',
      inputs: [],
      inputNote: '没有显式参数。它使用 __init__() 已保存在当前实例中的设备编号、分辨率、预热配置和图像控制。',
      output: {
        summary: '返回当前 OpenCVCameraSession 实例 self；此时摄像头已成功打开、配置并完成预热。',
      },
      source: {
        path: 'src/hardware/camera.py',
        startLine: 115,
        endLine: 148,
      },
      defaultExpanded: false,
      compact: false,
      steps: [
        {
          id: 'camera-open-import',
          text: '1. 动态导入 cv2；未安装时抛出 CameraCaptureError，并提示可改用 libcamera。',
          tone: 'error',
        },
        {
          id: 'camera-open-device',
          text: '2. 用设备索引创建 VideoCapture；设备打不开时先 release 临时句柄，再报告索引、连接或占用问题。',
          tone: 'error',
        },
        {
          id: 'camera-open-settings',
          text: '3. 按需设置宽高，并通过本文件私有配置逻辑应用格式、曝光、焦距等 OpenCV 属性。',
          tone: 'condition',
        },
        {
          id: 'camera-open-warmup-time',
          text: '4. warmup_seconds 大于 0 时等待曝光稳定。',
          tone: 'condition',
        },
        {
          id: 'camera-open-warmup-frames',
          text: '5. 保存 cv2 和设备句柄；若配置了 warmup_frames，则调用本文件私有读取逻辑丢弃初始缓冲帧，最后返回 self。',
          tone: 'condition',
        },
      ],
    },
    {
      id: 'camera-session-capture',
      fileId: 'file-hardware-camera',
      signature: 'OpenCVCameraSession.capture(output_path, *, warmup_frames=0, delay_seconds=0.0, burst_count=1) -> CaptureResult',
      meaning: '从已打开的 OpenCV 会话选择并保存一张候选帧。',
      inputs: [
        { name: 'output_path', summary: '当前照片要写入的准确文件路径。' },
        { name: 'warmup_frames', summary: '本次保存前额外读取并丢弃的帧数，默认 0。' },
        { name: 'delay_seconds', summary: '读取候选帧前等待的秒数，常用于等待舵机余振消失。' },
        { name: 'burst_count', summary: '要读取并参与清晰度比较的候选帧数量。', detail: '大于 1 时计算每张候选帧的清晰度，最终只保存分数最高的一张。' },
      ],
      output: {
        summary: '返回 CaptureResult，描述实际保存的这一张照片。',
        fields: [
          { name: 'path', summary: '照片成功写入的准确文件路径。' },
          { name: 'width', summary: '实际保存图像的像素宽度。' },
          { name: 'height', summary: '实际保存图像的像素高度。' },
          { name: 'device_index', summary: '本次使用的 OpenCV 摄像头设备编号。' },
          { name: 'backend', summary: '实际拍照后端；这里固定为 opencv。' },
          { name: 'sharpness', summary: '被选中候选帧的清晰度分数。', detail: '该分数用于同一批候选帧之间比较，数值越高通常代表边缘更清晰；它不是通用的百分制画质评分。' },
        ],
      },
      source: {
        path: 'src/hardware/camera.py',
        startLine: 150,
        endLine: 198,
      },
      defaultExpanded: false,
      compact: false,
      steps: [
        {
          id: 'camera-capture-validate',
          text: '1. 校验丢弃帧数、延时和候选数量，并确认会话已经成功打开；否则立即报错。',
          tone: 'error',
        },
        {
          id: 'camera-capture-delay',
          text: '2. delay_seconds 大于 0 时先等待，让舵机移动后的画面稳定。',
          tone: 'condition',
        },
        {
          id: 'camera-capture-path',
          text: '3. 将输出转换为 Path，并创建所需的父目录。',
          tone: 'normal',
        },
        {
          id: 'camera-capture-read',
          text: '4. 调用本文件私有读取逻辑：丢弃指定缓冲帧，再循环评分 burst_count 张候选图并选择拉普拉斯清晰度最高的一张。',
          tone: 'loop',
        },
        {
          id: 'camera-capture-write',
          text: '5. 使用 cv2.imwrite 保存最佳帧；写入失败时抛出 CameraCaptureError。',
          tone: 'error',
        },
        {
          id: 'camera-capture-result',
          text: '6. 从图像形状读取宽高，连同设备索引、opencv 后端和清晰度分数返回 CaptureResult。',
          tone: 'normal',
        },
      ],
    },
    {
      id: 'camera-session-close',
      fileId: 'file-hardware-camera',
      signature: 'OpenCVCameraSession.close() -> None',
      meaning: '释放当前会话拥有的 OpenCV 摄像头资源。',
      inputs: [],
      inputNote: '没有显式参数。它处理当前实例内部保存的 OpenCV 摄像头句柄。',
      output: {
        summary: '没有返回数据；如果设备已经打开则释放它，并把实例恢复为“未打开”状态。',
      },
      source: {
        path: 'src/hardware/camera.py',
        startLine: 200,
        endLine: 206,
      },
      defaultExpanded: false,
      compact: true,
      steps: [
        {
          id: 'camera-close-release',
          text: '1. 如果摄像头句柄存在就 release，并清空摄像头和 cv2 引用；重复 close 不会再次释放设备。',
          tone: 'finally',
        },
      ],
    },
    {
      id: 'camera-session-enter',
      fileId: 'file-hardware-camera',
      signature: 'OpenCVCameraSession.__enter__() -> OpenCVCameraSession',
      meaning: '实现 with 进入协议，并把打开后的会话交给 as 变量。',
      inputs: [],
      inputNote: '没有显式参数。Python 进入 with OpenCVCameraSession(...) 时自动在当前实例上调用它。',
      output: {
        summary: '返回 open() 得到的已打开会话，并交给 with ... as 后面的变量。',
      },
      source: {
        path: 'src/hardware/camera.py',
        startLine: 264,
        endLine: 265,
      },
      defaultExpanded: false,
      compact: true,
      steps: [
        {
          id: 'camera-enter-open',
          text: '1. 调用 open() 并原样返回，使 with 块得到已配置、已预热的摄像头。',
          tone: 'normal',
        },
      ],
    },
    {
      id: 'camera-session-exit',
      fileId: 'file-hardware-camera',
      signature: 'OpenCVCameraSession.__exit__(exc_type, exc, traceback) -> None',
      meaning: '成功进入 with 后，在代码块正常或异常退出时释放摄像头。',
      inputs: [
        { name: 'exc_type', summary: 'with 代码块抛出的异常类型；正常退出时为 None。' },
        { name: 'exc', summary: '实际异常对象；正常退出时为 None。' },
        { name: 'traceback', summary: '异常回溯信息；正常退出时为 None。', detail: '回溯记录异常经过的调用位置，供调试定位；本方法只接收它，不修改或吞掉异常。' },
      ],
      output: {
        summary: '没有返回数据；close() 完成清理后，with 块原有异常会继续向外传播。',
      },
      source: {
        path: 'src/hardware/camera.py',
        startLine: 267,
        endLine: 268,
      },
      defaultExpanded: false,
      compact: true,
      steps: [
        {
          id: 'camera-exit-close',
          text: '1. 调用 close() 释放会话资源；没有返回 True，所以不会静默压制 with 块中的异常。',
          tone: 'finally',
        },
      ],
    },
    {
      id: 'camera-capture-photo',
      fileId: 'file-hardware-camera',
      signature: 'capture_photo(output_path=None, *, output_dir=DEFAULT_CAPTURE_DIR, prefix=DEFAULT_PHOTO_PREFIX, extension=DEFAULT_PHOTO_EXTENSION, backend=DEFAULT_BACKEND, device_index=0, width=None, height=None, warmup_frames=5, warmup_seconds=0.5, settings=None, burst_count=1) -> CaptureResult',
      meaning: '执行一次独立拍照，并按后端选择或 auto 顺序尝试具体实现。',
      inputs: [
        { name: 'output_path', summary: '可选的准确目标文件；None 表示自动生成文件名。' },
        { name: 'output_dir', summary: '自动命名时使用的保存目录。' },
        { name: 'prefix', summary: '自动命名时使用的文件名前缀。' },
        { name: 'extension', summary: '自动命名时使用的扩展名，例如 .jpg。' },
        { name: 'backend', summary: '拍照后端：auto、opencv、libcamera 或 raspistill。', detail: 'auto 会按 OpenCV、libcamera、raspistill 的代码顺序尝试，某个后端成功后立即返回。' },
        { name: 'device_index', summary: 'OpenCV 摄像头设备编号；其他后端不使用。' },
        { name: 'width', summary: '可选的请求照片宽度，单位为像素。' },
        { name: 'height', summary: '可选的请求照片高度，单位为像素。' },
        { name: 'warmup_frames', summary: 'OpenCV 正式保存前丢弃的预热帧数量。' },
        { name: 'warmup_seconds', summary: '摄像头打开后等待稳定的秒数。' },
        { name: 'settings', summary: '可选的 OpenCVCameraSettings；只在 OpenCV 后端使用。' },
        { name: 'burst_count', summary: 'OpenCV 后端读取的候选帧数量。' },
      ],
      output: {
        summary: '返回 CaptureResult；指定后端失败会抛出 CameraCaptureError，auto 模式会在所有候选后端都失败后汇总原因再抛错。',
        fields: [
          { name: 'path', summary: '实际保存的照片路径。' },
          { name: 'width', summary: '实际图像宽度。' },
          { name: 'height', summary: '实际图像高度。' },
          { name: 'device_index', summary: 'OpenCV 设备编号；非 OpenCV 后端通常为 None。' },
          { name: 'backend', summary: '最终成功拍照的后端名称。' },
          { name: 'sharpness', summary: '可用时记录清晰度分数；某些后端为 None。' },
        ],
      },
      source: {
        path: 'src/hardware/camera.py',
        startLine: 283,
        endLine: 385,
      },
      defaultExpanded: false,
      compact: false,
      steps: [
        {
          id: 'photo-validate',
          text: '1. 校验预热帧数、预热秒数和 burst_count，非法时在打开设备前报错。',
          tone: 'error',
        },
        {
          id: 'photo-path',
          text: '2. 有 output_path 就使用准确路径，否则调用 build_photo_path() 生成时间戳路径，并创建父目录。',
          tone: 'condition',
        },
        {
          id: 'photo-opencv',
          text: '3. backend 为 auto 或 opencv 时调用本文件私有 OpenCV 单次拍照实现；明确指定 opencv 时失败会立即抛出，auto 时记录错误后继续。',
          tone: 'condition',
        },
        {
          id: 'photo-libcamera',
          text: '4. backend 为 auto 或 libcamera 时调用私有命令行实现；明确指定时失败立即抛出，auto 时保留错误并继续。',
          tone: 'condition',
        },
        {
          id: 'photo-raspistill',
          text: '5. backend 为 auto 或 raspistill 时按相同规则调用旧版树莓派命令行拍照实现。',
          tone: 'condition',
        },
        {
          id: 'photo-failed',
          text: '6. 没有后端成功时，合并各后端错误或报告不支持的后端，并给出设备、后端和占用服务排查建议。',
          tone: 'error',
        },
      ],
    },
    {
      id: 'servo-init',
      fileId: 'file-hardware-servo',
      signature: 'ServoController.__init__(pin, *, frequency=config.SERVO_PWM_FREQUENCY, min_duty=2.5, max_duty=12.5, settle_seconds=0.5, gpio=None)',
      meaning: '校验舵机参数并初始化当前 BCM 引脚的 PWM。',
      inputs: [
        { name: 'pin', summary: '舵机信号线连接的 BCM GPIO 引脚。', detail: '必须使用项目硬件资料确认的 BCM 编号，不能把 wiringPi 或物理针脚编号直接填进来。' },
        { name: 'frequency', summary: 'PWM 频率，默认使用项目配置值。', detail: 'PWM 会周期性输出脉冲。常见模拟舵机使用约 50 Hz，即每秒 50 个控制周期。' },
        { name: 'min_duty', summary: '0 度对应的最小占空比。', detail: '占空比表示一个 PWM 周期内高电平持续时间所占比例；不同舵机的安全范围可能不同。' },
        { name: 'max_duty', summary: '180 度对应的最大占空比。' },
        { name: 'settle_seconds', summary: '每次发送角度命令后等待舵机到位的秒数。' },
        { name: 'gpio', summary: '可选的 GPIO 模块；正常运行时为 None 并导入 RPi.GPIO。' },
      ],
      output: {
        summary: '__init__() 本身没有返回数据；ServoController(...) 构造表达式会得到已初始化 PWM 的舵机控制器实例。',
      },
      source: {
        path: 'src/hardware/servo.py',
        startLine: 41,
        endLine: 73,
      },
      defaultExpanded: false,
      compact: false,
      steps: [
        {
          id: 'servo-init-validate',
          text: '1. 要求引脚存在、频率大于 0、最小占空比小于最大占空比且等待时间非负；不合法时立即报错。',
          tone: 'error',
        },
        {
          id: 'servo-init-import',
          text: '2. 未注入 gpio 时动态导入 RPi.GPIO；不在树莓派环境时转换为 ServoError。',
          tone: 'error',
        },
        {
          id: 'servo-init-store',
          text: '3. 保存当前舵机拥有的引脚、频率、占空比、等待时间和 GPIO 对象。',
          tone: 'normal',
        },
        {
          id: 'servo-init-gpio',
          text: '4. 调用本文件私有初始化逻辑设置 BCM 模式和输出引脚，创建 PWM 并以 0 占空比启动。',
          tone: 'normal',
        },
      ],
    },
    {
      id: 'servo-move-to',
      fileId: 'file-hardware-servo',
      signature: 'ServoController.move_to(angle) -> ServoPosition',
      meaning: '把舵机转到目标角度，等待到位后停止保持脉冲。',
      inputs: [
        { name: 'angle', summary: '舵机要转到的目标角度，合法范围为 0～180 度。' },
      ],
      output: {
        summary: '返回 ServoPosition，记录本次已经完成的舵机动作。',
        fields: [
          { name: 'pin', summary: '执行动作的 BCM GPIO 引脚。' },
          { name: 'angle', summary: '本次请求并完成的目标角度。' },
          { name: 'duty_cycle', summary: '该角度换算得到的 PWM 占空比。', detail: '占空比决定每个 PWM 周期中高电平持续时间，舵机据此判断目标角度。' },
        ],
      },
      source: {
        path: 'src/hardware/servo.py',
        startLine: 75,
        endLine: 98,
      },
      defaultExpanded: false,
      compact: false,
      steps: [
        {
          id: 'servo-move-validate',
          text: '1. 将角度转成 float，并拒绝 0～180 度之外的值。',
          tone: 'error',
        },
        {
          id: 'servo-move-duty',
          text: '2. 调用本文件私有换算逻辑，把角度线性映射为 PWM 占空比。',
          tone: 'normal',
        },
        {
          id: 'servo-move-pwm',
          text: '3. 输出目标占空比并等待 settle_seconds，使舵机有时间转到位置。',
          tone: 'normal',
        },
        {
          id: 'servo-move-release',
          text: '4. 把占空比降为 0，减少抖动和发热，再返回 ServoPosition。',
          tone: 'normal',
        },
      ],
    },
    {
      id: 'servo-close',
      fileId: 'file-hardware-servo',
      signature: 'ServoController.close() -> None',
      meaning: '停止当前舵机 PWM，并只释放它拥有的 GPIO 引脚。',
      inputs: [],
      inputNote: '没有显式参数。它只处理当前 ServoController 自己拥有的 PWM 和 GPIO 引脚。',
      output: {
        summary: '没有返回数据；先停止 PWM，再只释放当前舵机拥有的 GPIO 引脚。',
      },
      source: {
        path: 'src/hardware/servo.py',
        startLine: 100,
        endLine: 106,
      },
      defaultExpanded: false,
      compact: true,
      steps: [
        {
          id: 'servo-close-release',
          text: '1. PWM 存在时先 stop 并清空引用，再调用 GPIO.cleanup(self.pin) 只释放当前舵机引脚。',
          tone: 'finally',
        },
      ],
    },
    {
      id: 'tool-parse-optional-int',
      fileId: 'file-tool-capture-panorama',
      signature: 'parse_optional_int(value: str) -> Optional[int]',
      meaning: '把可选 GPIO 参数转换成整数，并识别表示“禁用”的文本。',
      inputs: [
        { name: 'value', summary: '命令行中读到的原始字符串，例如 18 或 none。' },
      ],
      output: {
        summary: '返回 GPIO 整数编号；value 表示禁用时返回 None，无法转换时由 int() 抛出 ValueError。',
      },
      source: { path: 'src/tools/capture_panorama.py', startLine: 33, endLine: 38 },
      defaultExpanded: false,
      compact: true,
      steps: [
        { id: 'optional-int-disabled', text: '1. 将 value 转成小写；如果是 none、off 或 disabled，则返回 None，表示不配置这个可选引脚。', tone: 'condition' },
        { id: 'optional-int-number', text: '2. 其他文本交给 Python 内置 int() 转为整数；格式非法时不兜底，让 argparse 显示参数错误。', tone: 'error' },
      ],
    },
    {
      id: 'tool-parse-optional-float',
      fileId: 'file-tool-capture-panorama',
      signature: 'parse_optional_float(value: str) -> Optional[float]',
      meaning: '把可选角度参数转换成浮点数，并识别表示“禁用”的文本。',
      inputs: [
        { name: 'value', summary: '命令行中读到的原始字符串，例如 90、45.5 或 none。' },
      ],
      output: {
        summary: '返回浮点角度；value 表示禁用时返回 None，无法转换时由 float() 抛出 ValueError。',
      },
      source: { path: 'src/tools/capture_panorama.py', startLine: 41, endLine: 46 },
      defaultExpanded: false,
      compact: true,
      steps: [
        { id: 'optional-float-disabled', text: '1. 将 value 转成小写；如果是 none、off 或 disabled，则返回 None，表示不设置这个可选角度。', tone: 'condition' },
        { id: 'optional-float-number', text: '2. 其他文本交给 Python 内置 float() 转成小数；非法格式交由 argparse 报错。', tone: 'error' },
      ],
    },
    {
      id: 'camera-session-read-frame',
      fileId: 'file-hardware-camera',
      signature: 'OpenCVCameraSession._read_frame(warmup_frames: int)',
      meaning: '从已打开的 OpenCV 摄像头读取一帧，并先丢弃指定数量的缓冲帧。',
      inputs: [
        { name: 'warmup_frames', summary: '正式取图前额外读取的缓冲帧数量。', detail: '摄像头或驱动可能缓存旧画面。连续读取但不保存这些帧，可以提高最终帧与当前镜头方向一致的概率。' },
      ],
      output: { summary: '返回最后一张成功读取的 OpenCV 图像帧；一次都没读成功时抛出 CameraCaptureError。' },
      source: { path: 'src/hardware/camera.py', startLine: 208, endLine: 227 },
      defaultExpanded: false,
      compact: false,
      steps: [
        { id: 'read-frame-session', text: '1. 确认摄像头句柄已经存在；会话未打开时立即报错。', tone: 'error' },
        { id: 'read-frame-loop', text: '2. 至少读取 1 次，总次数为 warmup_frames + 1；成功帧覆盖之前结果，失败时等待 0.05 秒后继续。camera.read() 属于 OpenCV，不展开为项目方法。', tone: 'loop' },
        { id: 'read-frame-return', text: '3. 循环结束仍没有有效图像时报告设备编号；否则返回最后一次成功读取的帧。', tone: 'condition' },
      ],
    },
    {
      id: 'camera-session-read-best-frame',
      fileId: 'file-hardware-camera',
      signature: 'OpenCVCameraSession._read_best_frame(warmup_frames: int, burst_count: int)',
      meaning: '连续读取多张候选图，返回拉普拉斯清晰度分数最高的一张。',
      inputs: [
        { name: 'warmup_frames', summary: '评分前先读取并丢弃的帧数量。' },
        { name: 'burst_count', summary: '真正参与清晰度评分的候选帧数量。', detail: '候选数量越多，找到较清晰画面的机会越高，但每个拍摄角度需要更长时间。' },
      ],
      output: {
        summary: '返回二元组 (best_frame, best_score)。',
        fields: [
          { name: 'best_frame', summary: '候选帧中清晰度分数最高的 OpenCV 图像。' },
          { name: 'best_score', summary: '该图像的拉普拉斯方差分数。' },
        ],
      },
      source: { path: 'src/hardware/camera.py', startLine: 229, endLine: 262 },
      defaultExpanded: false,
      compact: false,
      steps: [
        { id: 'best-frame-session', text: '1. 同时确认摄像头和 cv2 已保存到会话；缺少任一对象都说明会话不可用。', tone: 'error' },
        { id: 'best-frame-loop', text: '2. 循环读取 warmup_frames + burst_count 次；读图失败短暂等待，预热范围内的帧直接跳过。', tone: 'loop' },
        { id: 'best-frame-score', text: '3. 对每张候选帧调用 sharpness_score()；分数高于当前最佳值时，替换最佳图像和分数。', tone: 'loop' },
        { id: 'best-frame-return', text: '4. 没有任何有效候选帧时抛错；否则返回最佳帧与分数。', tone: 'condition' },
      ],
    },
    {
      id: 'camera-build-photo-path',
      fileId: 'file-hardware-camera',
      signature: 'build_photo_path(output_dir=DEFAULT_CAPTURE_DIR, prefix=DEFAULT_PHOTO_PREFIX, extension=DEFAULT_PHOTO_EXTENSION) -> Path',
      meaning: '为未指定准确路径的单次拍照生成带时间戳的文件路径。',
      inputs: [
        { name: 'output_dir', summary: '自动照片要保存到的目录。' },
        { name: 'prefix', summary: '自动文件名的前缀，默认 photo。' },
        { name: 'extension', summary: '文件扩展名；没有点号时自动补上。' },
      ],
      output: { summary: '返回类似 captures/photo_20260711_153000.jpg 的 Path；这里只生成路径，不创建文件。' },
      source: { path: 'src/hardware/camera.py', startLine: 271, endLine: 280 },
      defaultExpanded: false,
      compact: true,
      steps: [
        { id: 'photo-path-extension', text: '1. 检查 extension 是否以点号开头，没有则补上。', tone: 'condition' },
        { id: 'photo-path-timestamp', text: '2. 读取当前时间并格式化为年月日_时分秒，和 prefix、extension 组合后放到 output_dir 下。', tone: 'normal' },
      ],
    },
    {
      id: 'camera-capture-with-opencv',
      fileId: 'file-hardware-camera',
      signature: '_capture_with_opencv(*, target_path, device_index, width, height, warmup_frames, warmup_seconds, settings, burst_count) -> CaptureResult',
      meaning: '用一个临时 OpenCV 会话完成一次独立拍照。',
      inputs: [
        { name: 'target_path', summary: '照片要写入的准确 Path。' },
        { name: 'device_index', summary: 'OpenCV 摄像头设备编号。' },
        { name: 'width', summary: '可选的请求宽度。' },
        { name: 'height', summary: '可选的请求高度。' },
        { name: 'warmup_frames', summary: '打开会话后丢弃的预热帧数。' },
        { name: 'warmup_seconds', summary: '设备打开后等待稳定的秒数。' },
        { name: 'settings', summary: '可选的 OpenCV 摄像头控制对象。' },
        { name: 'burst_count', summary: '参与清晰度选择的候选帧数量。' },
      ],
      output: { summary: '返回 OpenCVCameraSession.capture() 生成的 CaptureResult。' },
      source: { path: 'src/hardware/camera.py', startLine: 388, endLine: 407 },
      defaultExpanded: false,
      compact: false,
      steps: [
        { id: 'opencv-helper-session', text: '1. 用全部设备和预热参数构造 OpenCVCameraSession，并通过 with 自动打开会话。', tone: 'normal' },
        { id: 'opencv-helper-capture', text: '2. 调用会话的 capture() 保存 target_path，并传入 burst_count。', tone: 'normal' },
        { id: 'opencv-helper-close', text: '3. 正常或异常离开 with 时自动执行 __exit__()，释放摄像头。', tone: 'finally' },
      ],
    },
    {
      id: 'camera-apply-settings',
      fileId: 'file-hardware-camera',
      signature: 'apply_opencv_camera_settings(cv2, camera, settings: OpenCVCameraSettings) -> None',
      meaning: '把调用方请求的图像控制逐项应用到 OpenCV 摄像头。',
      inputs: [
        { name: 'cv2', summary: '已导入的 OpenCV 模块。' },
        { name: 'camera', summary: '已打开的 OpenCV VideoCapture 对象。' },
        { name: 'settings', summary: '调用方请求的 OpenCVCameraSettings。' },
      ],
      output: { summary: '没有返回数据；设备或驱动是否真正接受设置由 OpenCV 和硬件决定。' },
      source: { path: 'src/hardware/camera.py', startLine: 410, endLine: 438 },
      defaultExpanded: false,
      compact: false,
      steps: [
        { id: 'settings-fourcc', text: '1. fourcc 存在且恰好 4 个字符时，调用 OpenCV 生成格式编号并设置像素格式。', tone: 'condition' },
        { id: 'settings-basic', text: '2. 调用 _set_if_present() 设置帧率和缓冲区，只有属性和值都存在时才真正写入。', tone: 'normal' },
        { id: 'settings-auto', text: '3. 调用 _bool_to_number() 把可选自动对焦布尔值转成 OpenCV 数字，再设置自动对焦和自动曝光。', tone: 'normal' },
        { id: 'settings-quality', text: '4. 继续通过 _set_if_present() 应用亮度、对比度、饱和度、增益、曝光、焦距和锐化。', tone: 'loop' },
      ],
    },
    {
      id: 'camera-sharpness-score',
      fileId: 'file-hardware-camera',
      signature: 'sharpness_score(cv2, frame) -> float',
      meaning: '用拉普拉斯方差估算一张图像的相对清晰度。',
      inputs: [
        { name: 'cv2', summary: 'OpenCV 模块。' },
        { name: 'frame', summary: '要评分的彩色图像帧。' },
      ],
      output: { summary: '返回浮点清晰度分数；只适合同批候选帧相互比较，分数越高通常边缘越清晰。' },
      source: { path: 'src/hardware/camera.py', startLine: 441, endLine: 445 },
      defaultExpanded: false,
      compact: true,
      steps: [
        { id: 'sharpness-gray', text: '1. 使用 OpenCV 把 BGR 彩色图转换为灰度图。', tone: 'normal' },
        { id: 'sharpness-laplacian', text: '2. 计算灰度图的拉普拉斯结果及其方差；边缘变化越丰富，方差通常越大。cv2 内部算法属于第三方，不继续展开。', tone: 'normal' },
      ],
    },
    {
      id: 'camera-set-if-present',
      fileId: 'file-hardware-camera',
      signature: '_set_if_present(cv2, camera, property_name: str, value: Optional[float]) -> None',
      meaning: '只在属性和值都存在时设置一项 OpenCV 摄像头属性。',
      inputs: [
        { name: 'cv2', summary: 'OpenCV 模块。' },
        { name: 'camera', summary: '已打开的 VideoCapture 对象。' },
        { name: 'property_name', summary: 'cv2 上的属性常量名称，例如 CAP_PROP_FPS。' },
        { name: 'value', summary: '要设置的数值；None 表示调用方没有请求此项。' },
      ],
      output: { summary: '没有返回数据；缺值或当前 OpenCV 没有该属性时直接结束。' },
      source: { path: 'src/hardware/camera.py', startLine: 448, endLine: 453 },
      defaultExpanded: false,
      compact: true,
      steps: [
        { id: 'set-present-check', text: '1. value 为 None 或 cv2 不包含 property_name 时直接返回，避免写入无效属性。', tone: 'condition' },
        { id: 'set-present-value', text: '2. 读取 cv2 上的属性编号，把 value 转成 float 后调用第三方 camera.set()。', tone: 'normal' },
      ],
    },
    {
      id: 'camera-bool-to-number',
      fileId: 'file-hardware-camera',
      signature: '_bool_to_number(value: Optional[bool]) -> Optional[float]',
      meaning: '把可选布尔值转换成 OpenCV 属性接受的数字。',
      inputs: [
        { name: 'value', summary: 'True、False 或表示“保持现状”的 None。' },
      ],
      output: { summary: 'None 保持为 None，True 转成 1.0，False 转成 0.0。' },
      source: { path: 'src/hardware/camera.py', startLine: 456, endLine: 461 },
      defaultExpanded: false,
      compact: true,
      steps: [
        { id: 'bool-number-none', text: '1. value 为 None 时返回 None，让后续设置逻辑跳过该属性。', tone: 'condition' },
        { id: 'bool-number-value', text: '2. True 返回 1.0，False 返回 0.0。', tone: 'normal' },
      ],
    },
    {
      id: 'camera-capture-with-libcamera',
      fileId: 'file-hardware-camera',
      signature: '_capture_with_libcamera(*, target_path, width, height, warmup_seconds) -> CaptureResult',
      meaning: '调用树莓派 libcamera-still 命令保存一张照片。',
      inputs: [
        { name: 'target_path', summary: '照片目标路径。' },
        { name: 'width', summary: '可选的请求宽度。' },
        { name: 'height', summary: '可选的请求高度。' },
        { name: 'warmup_seconds', summary: '传给命令的预热秒数。' },
      ],
      output: { summary: '命令成功且文件非空时返回 backend 为 libcamera 的 CaptureResult。' },
      source: { path: 'src/hardware/camera.py', startLine: 464, endLine: 509 },
      defaultExpanded: false,
      compact: false,
      steps: [
        { id: 'libcamera-command', text: '1. 用 shutil.which() 查找 libcamera-still；找不到就报告命令未安装。', tone: 'error' },
        { id: 'libcamera-args', text: '2. 把预热秒数转成毫秒，构造无预览、输出路径和可选宽高参数。', tone: 'condition' },
        { id: 'libcamera-run', text: '3. 通过 Python subprocess.run() 执行系统命令；非零退出码转换成 CameraCaptureError。', tone: 'error' },
        { id: 'libcamera-result', text: '4. 再检查目标文件存在且非空，最后返回 CaptureResult。系统命令内部实现不属于项目代码。', tone: 'condition' },
      ],
    },
    {
      id: 'camera-capture-with-raspistill',
      fileId: 'file-hardware-camera',
      signature: '_capture_with_raspistill(*, target_path, width, height, warmup_seconds) -> CaptureResult',
      meaning: '调用旧版树莓派 raspistill 命令保存一张照片。',
      inputs: [
        { name: 'target_path', summary: '照片目标路径。' },
        { name: 'width', summary: '可选的请求宽度。' },
        { name: 'height', summary: '可选的请求高度。' },
        { name: 'warmup_seconds', summary: '传给命令的预热秒数。' },
      ],
      output: { summary: '命令成功且文件非空时返回 backend 为 raspistill 的 CaptureResult。' },
      source: { path: 'src/hardware/camera.py', startLine: 512, endLine: 557 },
      defaultExpanded: false,
      compact: false,
      steps: [
        { id: 'raspistill-command', text: '1. 查找 raspistill 命令；当前系统没有安装时立即报错。', tone: 'error' },
        { id: 'raspistill-args', text: '2. 把等待时间转成毫秒，构造无预览、目标路径和可选宽高参数。', tone: 'condition' },
        { id: 'raspistill-run', text: '3. 通过 subprocess.run() 执行命令，并把非零退出码及标准错误转换为 CameraCaptureError。', tone: 'error' },
        { id: 'raspistill-result', text: '4. 验证文件存在且非空后返回 CaptureResult；raspistill 内部拍照逻辑不展开。', tone: 'condition' },
      ],
    },
    {
      id: 'servo-setup-gpio',
      fileId: 'file-hardware-servo',
      signature: 'ServoController._setup_gpio() -> None',
      meaning: '初始化当前舵机引脚和 PWM 对象。',
      inputs: [],
      inputNote: '没有显式参数。它使用当前 ServoController 已保存的 gpio、pin 和 frequency。',
      output: { summary: '没有返回数据；完成后当前实例拥有一个已用 0 占空比启动的 PWM 对象。' },
      source: { path: 'src/hardware/servo.py', startLine: 108, endLine: 115 },
      defaultExpanded: false,
      compact: true,
      steps: [
        { id: 'setup-gpio-mode', text: '1. 调用 RPi.GPIO 设置 BCM 编号模式、关闭重复警告，并把当前 pin 配置为输出。', tone: 'normal' },
        { id: 'setup-gpio-pwm', text: '2. 以 frequency 创建当前引脚的 PWM 对象，再用 0 占空比启动。RPi.GPIO 和 PWM 内部实现属于第三方。', tone: 'normal' },
      ],
    },
    {
      id: 'servo-angle-to-duty',
      fileId: 'file-hardware-servo',
      signature: 'ServoController._angle_to_duty(angle: float) -> float',
      meaning: '把 0～180 度的舵机角度线性换算成 PWM 占空比。',
      inputs: [
        { name: 'angle', summary: '已经校验为 0～180 度的目标角度。' },
      ],
      output: { summary: '返回位于 min_duty 与 max_duty 之间的浮点占空比。' },
      source: { path: 'src/hardware/servo.py', startLine: 117, endLine: 121 },
      defaultExpanded: false,
      compact: true,
      steps: [
        { id: 'angle-duty-span', text: '1. 先计算占空比跨度 span = max_duty - min_duty。', tone: 'normal' },
        { id: 'angle-duty-map', text: '2. 使用 min_duty + span × angle ÷ 180 线性映射：0 度得到 min_duty，90 度位于中点，180 度得到 max_duty。', tone: 'normal' },
      ],
    },
  ],
  calls: [
    {
      id: 'call-main-parse-args',
      sourceMethodId: 'tool-main',
      sourceStepId: 'main-parse',
      targetMethodId: 'tool-parse-args',
      kind: 'certain',
      targetSide: 'right',
      lane: 0,
      label: '读取命令行参数',
    },
    {
      id: 'call-main-build-camera-settings',
      sourceMethodId: 'tool-main',
      sourceStepId: 'main-settings',
      targetMethodId: 'tool-build-camera-settings',
      kind: 'certain',
      targetSide: 'right',
      lane: -1,
      label: '构造摄像头配置',
    },
    {
      id: 'call-main-capture-panorama',
      sourceMethodId: 'tool-main',
      sourceStepId: 'main-capture',
      targetMethodId: 'task-capture-panorama',
      kind: 'certain',
      targetSide: 'left',
      lane: 0,
      label: '拍摄原始全景帧（stitch=False）',
    },
    {
      id: 'call-main-stitch-images',
      sourceMethodId: 'tool-main',
      sourceStepId: 'main-stitch',
      targetMethodId: 'task-stitch-images',
      kind: 'conditional',
      targetSide: 'left',
      lane: 1,
      label: '未指定 --no-stitch 时拼接',
    },
    {
      id: 'call-build-angle-validate',
      sourceMethodId: 'task-build-angle-sequence',
      sourceStepId: 'angles-validate',
      targetMethodId: 'task-validate-angle',
      kind: 'certain',
      targetSide: 'right',
      lane: 0,
      label: '校验起始角和终止角',
    },
    {
      id: 'call-capture-validate-angle',
      sourceMethodId: 'task-capture-panorama',
      sourceStepId: 'capture-validate',
      targetMethodId: 'task-validate-angle',
      kind: 'conditional',
      targetSide: 'right',
      lane: -1,
      label: '配置垂直角度时校验',
    },
    {
      id: 'call-capture-build-angles',
      sourceMethodId: 'task-capture-panorama',
      sourceStepId: 'capture-angles',
      targetMethodId: 'task-build-angle-sequence',
      kind: 'certain',
      targetSide: 'right',
      lane: -2,
      label: '生成拍摄角度序列',
    },
    {
      id: 'call-capture-build-session',
      sourceMethodId: 'task-capture-panorama',
      sourceStepId: 'capture-session',
      targetMethodId: 'task-build-session-dir',
      kind: 'certain',
      targetSide: 'right',
      lane: -3,
      label: '确定会话目录',
    },
    {
      id: 'call-capture-servo-init',
      sourceMethodId: 'task-capture-panorama',
      sourceStepId: 'capture-servo-init',
      targetMethodId: 'servo-init',
      kind: 'conditional',
      targetSide: 'left',
      lane: -3,
      label: '按配置创建水平和垂直舵机',
    },
    {
      id: 'call-capture-servo-move',
      sourceMethodId: 'task-capture-panorama',
      sourceStepId: 'capture-tilt',
      targetMethodId: 'servo-move-to',
      kind: 'conditional',
      targetSide: 'left',
      lane: -2,
      label: '垂直舵机移动到固定角度',
    },
    {
      id: 'call-capture-frames',
      sourceMethodId: 'task-capture-panorama',
      sourceStepId: 'capture-frames',
      targetMethodId: 'task-capture-frames',
      kind: 'certain',
      targetSide: 'right',
      lane: -4,
      label: '拍摄全部原始帧',
    },
    {
      id: 'call-capture-servo-close',
      sourceMethodId: 'task-capture-panorama',
      sourceStepId: 'capture-cleanup',
      targetMethodId: 'servo-close',
      kind: 'conditional',
      targetSide: 'left',
      lane: -1,
      label: 'finally 关闭已创建的舵机',
    },
    {
      id: 'call-capture-stitch',
      sourceMethodId: 'task-capture-panorama',
      sourceStepId: 'capture-stitch',
      targetMethodId: 'task-stitch-images',
      kind: 'conditional',
      targetSide: 'right',
      lane: 0,
      label: 'stitch=True 时任务内拼接',
    },
    {
      id: 'call-frames-opencv-session',
      sourceMethodId: 'task-capture-frames',
      sourceStepId: 'frames-backend',
      targetMethodId: 'task-capture-frames-opencv',
      kind: 'conditional',
      targetSide: 'right',
      lane: 0,
      label: 'OpenCV 后端复用一个会话',
    },
    {
      id: 'call-frames-servo-move',
      sourceMethodId: 'task-capture-frames',
      sourceStepId: 'frames-move',
      targetMethodId: 'servo-move-to',
      kind: 'conditional',
      targetSide: 'left',
      lane: -2,
      label: '逐角度移动水平舵机',
    },
    {
      id: 'call-frames-frame-path',
      sourceMethodId: 'task-capture-frames',
      sourceStepId: 'frames-path',
      targetMethodId: 'task-frame-path',
      kind: 'conditional',
      targetSide: 'right',
      lane: -1,
      label: '非 OpenCV 分支生成当前帧路径',
    },
    {
      id: 'call-frames-capture-photo',
      sourceMethodId: 'task-capture-frames',
      sourceStepId: 'frames-capture',
      targetMethodId: 'camera-capture-photo',
      kind: 'conditional',
      targetSide: 'left',
      lane: -1,
      label: '非 OpenCV 长会话分支单次拍照',
    },
    {
      id: 'call-opencv-session-init',
      sourceMethodId: 'task-capture-frames-opencv',
      sourceStepId: 'opencv-session-open',
      targetMethodId: 'camera-session-init',
      kind: 'certain',
      targetSide: 'left',
      lane: -4,
      label: '构造摄像头会话',
    },
    {
      id: 'call-opencv-session-enter',
      sourceMethodId: 'task-capture-frames-opencv',
      sourceStepId: 'opencv-session-open',
      targetMethodId: 'camera-session-enter',
      kind: 'certain',
      targetSide: 'left',
      lane: -3,
      label: 'with 隐式进入会话',
    },
    {
      id: 'call-camera-enter-open',
      sourceMethodId: 'camera-session-enter',
      sourceStepId: 'camera-enter-open',
      targetMethodId: 'camera-session-open',
      kind: 'certain',
      targetSide: 'right',
      lane: 0,
      label: '打开并预热摄像头',
    },
    {
      id: 'call-opencv-servo-move',
      sourceMethodId: 'task-capture-frames-opencv',
      sourceStepId: 'opencv-move',
      targetMethodId: 'servo-move-to',
      kind: 'conditional',
      targetSide: 'left',
      lane: -2,
      label: '逐角度移动水平舵机',
    },
    {
      id: 'call-opencv-frame-path',
      sourceMethodId: 'task-capture-frames-opencv',
      sourceStepId: 'opencv-path',
      targetMethodId: 'task-frame-path',
      kind: 'certain',
      targetSide: 'right',
      lane: -1,
      label: '生成当前帧路径',
    },
    {
      id: 'call-opencv-camera-capture',
      sourceMethodId: 'task-capture-frames-opencv',
      sourceStepId: 'opencv-capture',
      targetMethodId: 'camera-session-capture',
      kind: 'certain',
      targetSide: 'left',
      lane: -1,
      label: '从持续会话保存一帧',
    },
    {
      id: 'call-opencv-session-exit',
      sourceMethodId: 'task-capture-frames-opencv',
      sourceStepId: 'opencv-session-close',
      targetMethodId: 'camera-session-exit',
      kind: 'certain',
      targetSide: 'left',
      lane: 0,
      label: 'with 隐式退出会话',
    },
    {
      id: 'call-camera-exit-close',
      sourceMethodId: 'camera-session-exit',
      sourceStepId: 'camera-exit-close',
      targetMethodId: 'camera-session-close',
      kind: 'certain',
      targetSide: 'right',
      lane: -1,
      label: '释放 OpenCV 摄像头',
    },
    {
      id: 'call-stitch-create-stitcher',
      sourceMethodId: 'task-stitch-images',
      sourceStepId: 'stitch-create',
      targetMethodId: 'task-create-stitcher',
      kind: 'certain',
      targetSide: 'right',
      lane: 0,
      label: '创建兼容版本的拼接器',
    },
    {
      id: 'call-stitch-format-error',
      sourceMethodId: 'task-stitch-images',
      sourceStepId: 'stitch-run',
      targetMethodId: 'task-format-stitch-error',
      kind: 'conditional',
      targetSide: 'right',
      lane: -1,
      label: '拼接失败时解释状态码',
    },
    {
      id: 'call-frame-path-format-angle',
      sourceMethodId: 'task-frame-path',
      sourceStepId: 'frame-path-build',
      targetMethodId: 'task-format-angle',
      kind: 'certain',
      targetSide: 'right',
      lane: 0,
      label: '格式化文件名中的角度',
    },
    {
      id: 'call-parse-optional-int',
      sourceMethodId: 'tool-parse-args',
      sourceStepId: 'parse-register-options',
      targetMethodId: 'tool-parse-optional-int',
      kind: 'conditional',
      targetSide: 'right',
      lane: -1,
      label: '解析可选舵机引脚参数',
    },
    {
      id: 'call-parse-optional-float',
      sourceMethodId: 'tool-parse-args',
      sourceStepId: 'parse-register-options',
      targetMethodId: 'tool-parse-optional-float',
      kind: 'conditional',
      targetSide: 'right',
      lane: -2,
      label: '解析可选垂直角度参数',
    },
    {
      id: 'call-camera-open-apply-settings',
      sourceMethodId: 'camera-session-open',
      sourceStepId: 'camera-open-settings',
      targetMethodId: 'camera-apply-settings',
      kind: 'certain',
      targetSide: 'right',
      lane: -1,
      label: '应用 OpenCV 摄像头设置',
    },
    {
      id: 'call-camera-open-read-frame',
      sourceMethodId: 'camera-session-open',
      sourceStepId: 'camera-open-warmup-frames',
      targetMethodId: 'camera-session-read-frame',
      kind: 'conditional',
      targetSide: 'right',
      lane: -2,
      label: '丢弃会话初始预热帧',
    },
    {
      id: 'call-camera-capture-read-best',
      sourceMethodId: 'camera-session-capture',
      sourceStepId: 'camera-capture-read',
      targetMethodId: 'camera-session-read-best-frame',
      kind: 'certain',
      targetSide: 'right',
      lane: -3,
      label: '读取并选择最清晰候选帧',
    },
    {
      id: 'call-read-best-sharpness',
      sourceMethodId: 'camera-session-read-best-frame',
      sourceStepId: 'best-frame-score',
      targetMethodId: 'camera-sharpness-score',
      kind: 'conditional',
      targetSide: 'right',
      lane: -4,
      label: '为有效候选帧计算清晰度',
    },
    {
      id: 'call-photo-build-path',
      sourceMethodId: 'camera-capture-photo',
      sourceStepId: 'photo-path',
      targetMethodId: 'camera-build-photo-path',
      kind: 'conditional',
      targetSide: 'right',
      lane: -1,
      label: '未指定准确路径时自动命名',
    },
    {
      id: 'call-photo-opencv-helper',
      sourceMethodId: 'camera-capture-photo',
      sourceStepId: 'photo-opencv',
      targetMethodId: 'camera-capture-with-opencv',
      kind: 'conditional',
      targetSide: 'right',
      lane: -2,
      label: '尝试 OpenCV 单次拍照',
    },
    {
      id: 'call-photo-libcamera-helper',
      sourceMethodId: 'camera-capture-photo',
      sourceStepId: 'photo-libcamera',
      targetMethodId: 'camera-capture-with-libcamera',
      kind: 'conditional',
      targetSide: 'right',
      lane: -3,
      label: '尝试 libcamera-still 拍照',
    },
    {
      id: 'call-photo-raspistill-helper',
      sourceMethodId: 'camera-capture-photo',
      sourceStepId: 'photo-raspistill',
      targetMethodId: 'camera-capture-with-raspistill',
      kind: 'conditional',
      targetSide: 'right',
      lane: -4,
      label: '尝试 raspistill 拍照',
    },
    {
      id: 'call-opencv-helper-session-init',
      sourceMethodId: 'camera-capture-with-opencv',
      sourceStepId: 'opencv-helper-session',
      targetMethodId: 'camera-session-init',
      kind: 'certain',
      targetSide: 'right',
      lane: -5,
      label: '构造临时 OpenCV 会话',
    },
    {
      id: 'call-opencv-helper-session-enter',
      sourceMethodId: 'camera-capture-with-opencv',
      sourceStepId: 'opencv-helper-session',
      targetMethodId: 'camera-session-enter',
      kind: 'certain',
      targetSide: 'right',
      lane: -4,
      label: 'with 隐式打开会话',
    },
    {
      id: 'call-opencv-helper-capture',
      sourceMethodId: 'camera-capture-with-opencv',
      sourceStepId: 'opencv-helper-capture',
      targetMethodId: 'camera-session-capture',
      kind: 'certain',
      targetSide: 'right',
      lane: -3,
      label: '保存单张候选最佳帧',
    },
    {
      id: 'call-opencv-helper-session-exit',
      sourceMethodId: 'camera-capture-with-opencv',
      sourceStepId: 'opencv-helper-close',
      targetMethodId: 'camera-session-exit',
      kind: 'certain',
      targetSide: 'right',
      lane: -2,
      label: 'with 隐式释放会话',
    },
    {
      id: 'call-settings-set-present',
      sourceMethodId: 'camera-apply-settings',
      sourceStepId: 'settings-basic',
      targetMethodId: 'camera-set-if-present',
      kind: 'certain',
      targetSide: 'right',
      lane: -2,
      label: '按属性是否存在逐项设置',
    },
    {
      id: 'call-settings-bool-number',
      sourceMethodId: 'camera-apply-settings',
      sourceStepId: 'settings-auto',
      targetMethodId: 'camera-bool-to-number',
      kind: 'certain',
      targetSide: 'right',
      lane: -3,
      label: '把自动对焦布尔值转成数字',
    },
    {
      id: 'call-settings-quality-set-present',
      sourceMethodId: 'camera-apply-settings',
      sourceStepId: 'settings-quality',
      targetMethodId: 'camera-set-if-present',
      kind: 'certain',
      targetSide: 'right',
      lane: -4,
      label: '逐项应用图像质量设置',
    },
    {
      id: 'call-servo-init-setup-gpio',
      sourceMethodId: 'servo-init',
      sourceStepId: 'servo-init-gpio',
      targetMethodId: 'servo-setup-gpio',
      kind: 'certain',
      targetSide: 'right',
      lane: -1,
      label: '初始化 BCM 引脚和 PWM',
    },
    {
      id: 'call-servo-move-angle-duty',
      sourceMethodId: 'servo-move-to',
      sourceStepId: 'servo-move-duty',
      targetMethodId: 'servo-angle-to-duty',
      kind: 'certain',
      targetSide: 'right',
      lane: -2,
      label: '线性换算角度对应的占空比',
    },
  ],
};
