const input = (name, summary, detail) => ({ name, summary, ...(detail ? { detail } : {}) });
const output = (summary, fields = []) => ({ summary, ...(fields.length ? { fields } : {}) });
const step = (id, text, tone = 'normal') => ({ id, text, tone });
const method = (
  id,
  fileId,
  signature,
  meaning,
  inputs,
  result,
  startLine,
  endLine,
  steps,
  defaultExpanded = false,
) => ({
  id,
  fileId,
  signature,
  meaning,
  inputs,
  output: result,
  source: { path: FILE_PATHS[fileId], startLine, endLine },
  defaultExpanded,
  steps,
});

const FILE_PATHS = {
  'file-grid-navigation': 'src/tasks/grid_navigation.py',
  'file-edge-follow': 'src/tasks/edge_follow.py',
  'file-line-follow': 'src/tasks/line_follow.py',
  'file-reverse-radar': 'src/tasks/reverse_radar.py',
  'file-astar': 'src/algorithms/astar.py',
  'file-motor': 'src/hardware/motor.py',
  'file-line-sensor': 'src/hardware/line_sensor.py',
  'file-buzzer': 'src/hardware/buzzer.py',
};

export const mapData = {
  directories: [
    {
      id: 'dir-src',
      name: 'src',
      description: '网格导航功能的项目源码根目录；地图只展示从唯一入口真实可达的项目自有方法。',
      parentId: null,
    },
    {
      id: 'dir-algorithms',
      name: 'algorithms',
      description: '纯算法层：校验网格并用 A* 规划节点路径。',
      parentId: 'dir-src',
    },
    {
      id: 'dir-tasks',
      name: 'tasks',
      description: '任务编排层：维护可信节点状态、执行单边循迹并在阻塞后倒车恢复。',
      parentId: 'dir-src',
    },
    {
      id: 'dir-hardware',
      name: 'hardware',
      description: '硬件边界层：读取巡线 GPIO、控制电机与蜂鸣器；GPIO/PWM 库内部不再展开。',
      parentId: 'dir-src',
    },
  ],
  files: [
    {
      id: 'file-astar',
      directoryId: 'dir-algorithms',
      name: 'astar.py',
      path: FILE_PATHS['file-astar'],
      description: '校验矩形网格、障碍节点和阻塞边，并搜索最短四连通路径。',
    },
    {
      id: 'file-grid-navigation',
      directoryId: 'dir-tasks',
      name: 'grid_navigation.py',
      path: FILE_PATHS['file-grid-navigation'],
      description: '唯一功能入口所在文件；只在确认到达节点或恢复成功后更新可信状态。',
    },
    {
      id: 'file-edge-follow',
      directoryId: 'dir-tasks',
      name: 'edge_follow.py',
      path: FILE_PATHS['file-edge-follow'],
      description: '执行一条规划边：对准方向、离开节点、循迹到下一节点，阻塞时倒车恢复。',
    },
    {
      id: 'file-line-follow',
      directoryId: 'dir-tasks',
      name: 'line_follow.py',
      path: FILE_PATHS['file-line-follow'],
      description: '把四路巡线读数转换为节点、直行、修正或寻线动作。',
    },
    {
      id: 'file-reverse-radar',
      directoryId: 'dir-tasks',
      name: 'reverse_radar.py',
      path: FILE_PATHS['file-reverse-radar'],
      description: '可选倒车提示：按缓存距离非阻塞地控制蜂鸣器节奏。',
    },
    {
      id: 'file-motor',
      directoryId: 'dir-hardware',
      name: 'motor.py',
      path: FILE_PATHS['file-motor'],
      description: '将前进、后退、转向和刹车转换为 GPIO 方向与 PWM 占空比。',
    },
    {
      id: 'file-line-sensor',
      directoryId: 'dir-hardware',
      name: 'line_sensor.py',
      path: FILE_PATHS['file-line-sensor'],
      description: '读取四路红外 GPIO，并归一化为是否检测到黑线。',
    },
    {
      id: 'file-buzzer',
      directoryId: 'dir-hardware',
      name: 'buzzer.py',
      path: FILE_PATHS['file-buzzer'],
      description: '通过一个 GPIO 输出控制有源蜂鸣器开关。',
    },
  ],
  methods: [
    method(
      'grid-navigate', 'file-grid-navigation',
      'GridNavigator.navigate(self, start, end, initial_heading)',
      '唯一功能入口：循环规划下一条边，依据执行结果推进、重规划或安全失败。',
      [
        input('start', '起点零基坐标 (row, col)。', '入口立即把它设为可信 current_node；只有确认到达下一节点时才会改变。'),
        input('end', '目标零基坐标 (row, col)。'),
        input('initial_heading', '起点处可信朝向。', '只允许 north、east、south、west；用于把路径中的相邻坐标转换为转向动作。'),
      ],
      output('返回导航终态字符串。', [
        input('arrived', '可信节点已等于目标节点。'),
        input('no_path', '考虑静态和动态阻塞边后，A* 已无可行路径。'),
        input('failed', '单边执行或倒车恢复未得到可信成功状态。'),
      ]),
      76, 181,
      [
        step('nav-validate', '1. 校验 initial_heading；不在四个允许值中时立即抛出 ValueError。', 'error'),
        step('nav-initialize', '2. 保存起点、终点和初始朝向，清空上次运行留下的动态阻塞边并记录启动日志。'),
        step('nav-plan-loop', '3. 只要当前可信节点还不是目标，就合并静态/动态阻塞边并调用 A* 重新规划。', 'loop'),
        step('nav-no-path', '4. A* 返回 None 时立即刹车，记录当前位置并返回 no_path。', 'condition'),
        step('nav-prepare-edge', '5. 取路径的第二个节点，计算目标朝向和无向规划边，并把路径格式化为 A1 风格日志。'),
        step('nav-execute-edge', '6. 调用 EdgeFollower 执行这一条边，兼容读取结构化结果或旧字符串状态并记录结果。'),
        step('nav-reached', '7. 确认到达下一节点时，才更新 current_node/current_heading，然后进入下一轮规划。', 'condition'),
        step('nav-blocked', '8. 确认规划边被阻塞时，登记动态阻塞边，并调用倒车恢复返回原可信节点。', 'condition'),
        step('nav-recovery-failed', '9. 倒车没有确认回到起点时刹车并返回 failed；当前位置不会被猜测更新。', 'error'),
        step('nav-recovered', '10. 恢复成功后采用结果中的最终朝向；缺失时使用本次规划朝向，随后重新规划。', 'condition'),
        step('nav-edge-failed', '11. 其它单边状态都视为失败：刹车、记录状态并返回 failed。', 'error'),
        step('nav-arrived', '12. 循环因可信节点等于目标而结束时刹车，记录到达日志并返回 arrived。', 'finally'),
      ],
      true,
    ),
    method(
      'grid-log', 'file-grid-navigation', 'GridNavigator._log(self, message)',
      '仅在配置了调试回调时输出一条导航日志。',
      [input('message', '准备输出的调试文本。')], output('无返回值；未配置回调时不产生输出。'),
      71, 74,
      [step('grid-log-condition', '1. _debug 不为 None 时调用注入的回调；回调内部属于外部边界，不再展开。', 'condition')],
    ),
    method(
      'grid-all-blocked', 'file-grid-navigation', 'GridNavigator._all_blocked_edges(self)',
      '合并本次导航已知的全部不可通行边。', [],
      output('返回静态阻塞边与本次发现的动态阻塞边之并集。'),
      183, 184,
      [step('grid-blocked-union', '1. 使用集合并集生成新的 blocked_edges 集合。')],
    ),
    method(
      'grid-fmt-node', 'file-grid-navigation', '_fmt_node(node)',
      '把一个零基坐标转换成便于现场阅读的 A1 风格文本。',
      [input('node', '一个 (row, col) 网格坐标。')], output('返回单个 A1 风格节点字符串。'),
      187, 189,
      [step('fmt-node-format', '1. 把单节点列表交给 format_path()，并取第一项。')],
    ),
    method(
      'grid-result-status', 'file-grid-navigation', '_result_status(result)',
      '统一读取新版结构化边结果与旧版字符串结果的状态。',
      [input('result', 'EdgeExecutionResult 或旧调用方直接返回的状态字符串。')],
      output('对象有 status 属性时返回该属性，否则原样返回 result。'),
      192, 193,
      [step('result-status-branch', '1. 检查 status 属性；存在则读取，不存在则把 result 当作状态。', 'condition')],
    ),
    method(
      'grid-result-heading', 'file-grid-navigation', '_result_final_heading(result, default=None)',
      '从恢复结果中取得可信最终朝向，并使用明确传入的默认值。',
      [input('result', '倒车恢复结果。'), input('default', '结果未提供有效 final_heading 时采用的朝向。')],
      output('返回结果中的非空 final_heading，否则返回 default。'),
      196, 197,
      [step('result-heading-read', '1. 读取 final_heading 属性；属性缺失或值为空时返回 default。', 'condition')],
    ),
    method(
      'grid-heading-between', 'file-grid-navigation', '_heading_between(current_node, next_node)',
      '把相邻网格坐标的位移转换为北、南、东、西朝向。',
      [input('current_node', '当前可信坐标。'), input('next_node', '规划路径上的下一个相邻坐标。')],
      output('返回 north/east/south/west；两点不相邻时抛出 ValueError。'),
      200, 219,
      [
        step('heading-unpack', '1. 拆出两个坐标的 row 与 col。'),
        step('heading-compare', '2. 按上、下、右、左四种单格位移依次返回对应朝向。', 'condition'),
        step('heading-error', '3. 四种相邻关系都不满足时抛出 ValueError，防止把非法路径变成动作。', 'error'),
      ],
    ),

    method(
      'astar-search', 'file-astar', 'astar(grid, start, end, blocked_edges=None)',
      '在矩形四连通网格中搜索避开障碍节点和阻塞边的最短路径。',
      [
        input('grid', '只含 A（可通行）和 X（障碍）的矩形二维网格。'),
        input('start', '起点零基坐标。'), input('end', '终点零基坐标。'),
        input('blocked_edges', '不可通行无向边集合。', '每条边必须是包含两个相邻坐标的 frozenset；动态发现的障碍也通过这里进入规划。'),
      ],
      output('找到时返回包含起点和终点的坐标列表；无路可走时返回 None。'),
      50, 113,
      [
        step('astar-validate', '1. 校验网格、起终点和阻塞边契约；起点或终点落在 X 上也立即报错。'),
        step('astar-init', '2. 创建起始 Node，以曼哈顿距离作为 h，并初始化最小堆、最佳代价与关闭集合。'),
        step('astar-loop', '3. 循环弹出总代价最小的节点；已关闭的重复节点直接跳过。', 'loop'),
        step('astar-found', '4. 当前节点等于终点时沿 parent 回溯，再反转得到正向路径。', 'condition'),
        step('astar-neighbors-step', '5. 枚举上下左右邻居，跳过已关闭、X 障碍或 blocked_edges 中的边。', 'loop'),
        step('astar-relax', '6. 新代价更优时创建子 Node、更新最佳代价并压入最小堆。', 'condition'),
        step('astar-none', '7. 最小堆耗尽仍未到终点时返回 None。', 'condition'),
      ],
    ),
    method(
      'astar-node-f', 'file-astar', 'Node.f(self)',
      'A* Node 的只读属性：计算排序所需的总代价。', [], output('返回 g + h。'),
      35, 37, [step('node-f-sum', '1. 把起点到当前节点的真实代价 g 与估计代价 h 相加。')],
    ),
    method(
      'astar-heuristic', 'file-astar', 'heuristic(a, b)',
      '计算只允许上下左右移动时的曼哈顿距离。',
      [input('a', '第一个 (row, col) 坐标。'), input('b', '第二个 (row, col) 坐标。')],
      output('返回行差绝对值与列差绝对值之和。'), 40, 47,
      [step('heuristic-distance', '1. 计算 |row 差| + |col 差|。')],
    ),
    method(
      'astar-format-path', 'file-astar', 'format_path(path)',
      '把零基坐标路径转换为 A1、B2 形式的展示文本。',
      [input('path', '坐标路径列表。')], output('返回与输入同序的字符串列表。'), 125, 134,
      [step('format-path-loop', '1. 逐个坐标把 row 转成大写字母、col 加 1，再追加到结果列表。', 'loop')],
    ),
    method(
      'astar-validate-grid', 'file-astar', '_validate_grid(grid)',
      '在 A* 信任边界确认网格非空、矩形且字符合法。',
      [input('grid', '外部传入的二维网格。')], output('合法时返回 (height, width)，否则抛出 ValueError。'), 137, 150,
      [
        step('validate-grid-nonempty', '1. 网格或首行为空时立即报错。', 'error'),
        step('validate-grid-loop', '2. 逐行检查宽度一致，并逐格确认值只能是 A 或 X。', 'loop'),
        step('validate-grid-size', '3. 返回实际行数和列数。'),
      ],
    ),
    method(
      'astar-validate-coordinate', 'file-astar', '_validate_coordinate(name, coordinate, height, width)',
      '确认坐标是两个整数构成的 tuple，且位于网格范围内。',
      [input('name', '错误消息中的字段名。'), input('coordinate', '待校验坐标。'), input('height', '网格行数。'), input('width', '网格列数。')],
      output('合法时无返回值；不合法时抛出 ValueError。'), 153, 162,
      [step('validate-coordinate-shape', '1. 检查 tuple 类型、长度 2、row/col 均为整数。', 'condition'), step('validate-coordinate-range', '2. 检查坐标没有越过四条网格边界。', 'condition')],
    ),
    method(
      'astar-validate-edges', 'file-astar', '_validate_blocked_edges(blocked_edges, height, width)',
      '规范并校验不可通行边集合。',
      [input('blocked_edges', 'None 或 frozenset 边的集合。'), input('height', '网格行数。'), input('width', '网格列数。')],
      output('返回新的已校验边集合。'), 165, 182,
      [
        step('validate-edges-none', '1. 输入为 None 时返回空集合。', 'condition'),
        step('validate-edges-loop', '2. 逐边检查 frozenset 类型、恰有两点、两点坐标有效且曼哈顿距离为 1。', 'loop'),
        step('validate-edges-return', '3. 返回去重后的有效边集合。'),
      ],
    ),
    method(
      'astar-neighbors', 'file-astar', '_neighbors(position, height, width)',
      '按左、上、右、下顺序产生仍在网格内的四连通邻居。',
      [input('position', '当前坐标。'), input('height', '网格行数。'), input('width', '网格列数。')],
      output('生成零到四个合法相邻坐标。'), 185, 195,
      [step('neighbors-loop', '1. 枚举四个候选坐标，只 yield 未越界者。', 'loop')],
    ),

    method(
      'edge-execute', 'file-edge-follow', 'EdgeFollower.execute_planned_edge(self, current_heading, target_heading, max_seconds)',
      '在总超时内完成对准、离开起点和沿边循迹。',
      [input('current_heading', '进入边执行前的可信朝向。'), input('target_heading', '规划边要求的朝向。'), input('max_seconds', '转向、离点和行边共享的总超时秒数。')],
      output('返回 EdgeExecutionResult，包含状态、可选最终朝向和失败原因。'), 250, 283,
      [
        step('edge-exec-validate', '1. max_seconds 不大于 0 时抛出 ValueError。', 'error'),
        step('edge-exec-start', '2. 计算统一 deadline 并记录开始日志。'),
        step('edge-exec-align', '3. 对准目标朝向；超时失败时刹车并返回 turn_failed。', 'condition'),
        step('edge-exec-leave', '4. 保护性离开当前节点；失败时刹车并返回 leave_node_failed。', 'condition'),
        step('edge-exec-travel', '5. 沿规划边循迹，把到达、阻塞、丢线或超时结果记录后返回。'),
      ],
    ),
    method(
      'edge-recover', 'file-edge-follow', 'EdgeFollower.recover_to_start_node(self, return_heading=None, max_seconds=None)',
      '发现边阻塞后倒车沿原边返回起始可信节点。',
      [input('return_heading', '恢复完成后应保持的朝向；兼容旧数值位置参数。'), input('max_seconds', '倒车恢复总超时秒数。')],
      output('成功返回 recovered_to_start_node；其它底层状态统一包装为 recovery_failed。'), 294, 335,
      [
        step('recover-compat', '1. 兼容旧调用：第一个参数为数字且 max_seconds 为空时，把它当作超时。', 'condition'),
        step('recover-validate', '2. 超时缺失或不大于 0 时抛出 ValueError。', 'error'),
        step('recover-run', '3. 计算 deadline，记录日志并执行不使用前向障碍门的倒车循迹。'),
        step('recover-success', '4. 底层确认回到起点时记录并原样返回。', 'condition'),
        step('recover-failed', '5. 其它结果先刹车，再包装为 recovery_failed 并保留底层原因。', 'error'),
        step('recover-finally', '6. 无论成功、失败或异常，只要配置了倒车雷达就调用 stop() 静音。', 'finally'),
      ],
    ),
    method(
      'edge-log', 'file-edge-follow', 'EdgeFollower._log(self, message)',
      '仅在配置了调试回调时输出一条边执行日志。', [input('message', '阶段或结果日志。')],
      output('无返回值。'), 245, 248,
      [step('edge-log-condition', '1. _debug 存在时调用注入回调；回调内部不展开。', 'condition')],
    ),
    method(
      'edge-align', 'file-edge-follow', 'EdgeFollower._align_to_heading(self, current_heading, target_heading, deadline)',
      '根据两个罗盘朝向决定不转、右转、左转或左转 180°。',
      [input('current_heading', '当前朝向。'), input('target_heading', '目标朝向。'), input('deadline', '整条边共用的绝对截止时间。')],
      output('未超时且粗转完成时返回 True；超时返回 False；朝向非法时抛错。'), 337, 368,
      [
        step('align-unknown', '1. 任一朝向为 None 时跳过粗转，只检查是否仍在截止时间前。', 'condition'),
        step('align-validate', '2. 非 None 朝向不在四个允许值中时抛出 ValueError。', 'error'),
        step('align-diff', '3. 用朝向索引差的模 4 结果判断转向类型。'),
        step('align-branch', '4. 差值 0 不转；1 右转；2 左转 180°；3 左转，并记录相应日志。', 'condition'),
      ],
    ),
    method(
      'edge-rough-turn', 'file-edge-follow', 'EdgeFollower._rough_turn(self, left, seconds, deadline)',
      '用固定时长原地旋转完成粗略转向，并在结束后刹车。',
      [input('left', 'True 左旋，False 右旋。'), input('seconds', '粗转持续秒数。'), input('deadline', '整条边的绝对截止时间。')],
      output('结束时仍早于 deadline 返回 True，否则返回 False。'), 370, 380,
      [step('rough-timeout', '1. 开始时已经超时则直接返回 False。', 'condition'), step('rough-spin', '2. seconds 大于 0 时按 left 选择原地左旋或右旋，并等待指定时间。', 'condition'), step('rough-brake', '3. 刹车并再次检查 deadline。', 'finally')],
    ),
    method(
      'edge-leave-node', 'file-edge-follow', 'EdgeFollower._leave_node(self, deadline)',
      '保护性驶离当前节点，避免把起点的宽黑线误认成下一节点。',
      [input('deadline', '整条边的绝对截止时间。')], output('满足最短离点时间且连续看到普通线时返回 True；否则返回 False。'), 382, 422,
      [
        step('leave-init', '1. 记录开始时间，清空连续普通线计数和上次日志摘要。'),
        step('leave-loop', '2. 在总 deadline 和 line_acquire_timeout 内反复读取巡线 GPIO并执行一次循迹动作。', 'loop'),
        step('leave-classify', '3. 节点读数清零计数并强制向前；普通线累加；丢线清零。', 'condition'),
        step('leave-success', '4. 已经过最短保护时间且连续普通线样本达标时返回 True。', 'condition'),
        step('leave-failed', '5. 循环超时后记录最后状态并返回 False。', 'error'),
      ],
    ),
    method(
      'edge-travel', 'file-edge-follow', 'EdgeFollower._travel_edge(self, deadline, final_heading=None)',
      '在规划边上前向循迹，确认下一节点、障碍、丢线或超时。',
      [input('deadline', '整条边的绝对截止时间。'), input('final_heading', '成功或失败结果携带的规划朝向。')],
      output('返回 reached_next_node、blocked_on_planned_edge、line_lost 或 timeout 的结构化结果。'), 424, 492,
      [
        step('travel-start', '1. 记录阶段日志并重置只在前向行边阶段生效的障碍门。'),
        step('travel-loop', '2. 在 deadline 前反复执行一次闭环循迹。', 'loop'),
        step('travel-node', '3. 连续节点样本达到阈值时短推到节点中心，返回 reached_next_node。', 'condition'),
        step('travel-blocked', '4. 只有稳定循迹且障碍门确认阻塞时刹车，返回 blocked_on_planned_edge。', 'condition'),
        step('travel-lost', '5. 更新丢线计时；持续丢线达到阈值时刹车并返回 line_lost。', 'condition'),
        step('travel-timeout', '6. deadline 到达后刹车并返回 timeout。', 'error'),
      ],
    ),
    method(
      'edge-reverse', 'file-edge-follow', 'EdgeFollower._reverse_to_node_without_obstacle(self, deadline, final_heading=None)',
      '倒车循迹回到原节点；恢复阶段刻意不使用前向障碍门封锁新边。',
      [input('deadline', '恢复阶段绝对截止时间。'), input('final_heading', '结果中保留的朝向。')],
      output('返回 recovered_to_start_node、line_lost 或 timeout。'), 494, 558,
      [
        step('reverse-start', '1. 初始化节点计数、丢线计时和日志摘要。'),
        step('reverse-loop', '2. deadline 前循环；配置倒车雷达时先 tick，再读取巡线传感器并执行反向修正。', 'loop'),
        step('reverse-node', '3. 连续节点样本达标时居中并返回 recovered_to_start_node。', 'condition'),
        step('reverse-lost', '4. 持续丢线达到阈值时刹车并返回 line_lost。', 'condition'),
        step('reverse-timeout', '5. deadline 到达后刹车并返回 timeout。', 'error'),
      ],
    ),
    method(
      'edge-apply-reverse', 'file-edge-follow', 'EdgeFollower._apply_reverse_reading(self, reading)',
      '沿用巡线判断，但把动作映射成倒车方向的电机命令。',
      [input('reading', '已经读取的一次四路巡线结果。')], output('返回描述读数、动作和线状态的 LineStepResult。'), 560, 585,
      [
        step('reverse-decide', '1. 调用 decide_line_action() 取得与前向巡线一致的读数语义。'),
        step('reverse-command', '2. 节点或寻线状态刹车；直线双轮后退；左右偏差用单侧后退修正。', 'condition'),
        step('reverse-result', '3. 分别计算节点、见线和居中标记，构造不可变结果对象。'),
      ],
    ),
    method(
      'edge-center-node', 'file-edge-follow', 'EdgeFollower._center_on_node(self)',
      '确认节点后短暂向前推，使车体更接近节点中心，然后刹车。', [], output('无返回值；结束时电机已刹车。'), 587, 594,
      [step('center-push', '1. node_center_seconds 大于 0 时按巡线直行速度前进并等待。', 'condition'), step('center-brake', '2. 无论是否短推都调用刹车。', 'finally')],
    ),
    method(
      'edge-stable-tracking', 'file-edge-follow', 'EdgeFollower._stable_tracking(self, result)',
      '判断当前是否稳定沿普通线行驶，决定障碍读数能否被信任。',
      [input('result', '本轮巡线结果。')], output('见线、非节点且不是左旋寻线时返回 True。'), 596, 601,
      [step('stable-check', '1. 同时检查 line_seen、is_node 与 action。', 'condition')],
    ),
    method(
      'edge-update-loss', 'file-edge-follow', 'EdgeFollower._update_line_loss(self, result, lost_since)',
      '维护连续丢线开始时间。', [input('result', '本轮巡线结果。'), input('lost_since', '此前丢线起始时刻或 None。')],
      output('重新见线返回 None；首次丢线返回当前时刻；持续丢线保留旧时刻。'), 603, 608,
      [step('loss-seen', '1. 见线时清除丢线计时。', 'condition'), step('loss-start', '2. 首次丢线记录当前单调时钟，否则保留原时刻。', 'condition')],
    ),
    method(
      'edge-reading-summary', 'file-edge-follow', '_reading_summary(result)',
      '把一轮巡线结果压缩成现场调试日志。', [input('result', '含 reading/action/is_node/line_seen 的结果对象。')],
      output('返回 LO、LI、RI、RO、node、line、action 拼成的字符串。'), 611, 626,
      [step('summary-format', '1. 把布尔读数转为 0/1 并拼接动作名称。')],
    ),
    method(
      'gate-start', 'file-edge-follow', 'ObstacleGate.start_edge(self)',
      '为新规划边重置障碍去抖状态。', [], output('无返回值。'), 110, 114,
      [step('gate-reset', '1. 记录开始时刻，并把安全样本数和命中样本数清零。')],
    ),
    method(
      'gate-check', 'file-edge-follow', 'ObstacleGate.check_blocked(self)',
      '经过延迟、清空和连续命中三道条件后才确认当前边阻塞。', [], output('只有达到确认阈值时返回 True，其余情况返回 False。'), 116, 139,
      [
        step('gate-unavailable', '1. 没有传感器、尚未 start_edge 或仍在 arm_delay 内时返回 False。', 'condition'),
        step('gate-safe', '2. 当前无障碍时累加安全样本、清零命中并返回 False。', 'condition'),
        step('gate-not-armed', '3. 安全样本还未达到 clear_samples 时忽略障碍命中。', 'condition'),
        step('gate-confirm', '4. 累加连续障碍命中，达到 confirm_samples 才返回 True。', 'condition'),
      ],
    ),
    method(
      'cached-obstacle-read', 'file-edge-follow', 'CachedObstacleSensor.is_obstructed(self)',
      '读取后台超声波监控已经缓存的障碍布尔值，不在循迹循环中重新测距。', [],
      output('返回 source.obstacle_detected 的布尔值。'), 70, 72,
      [step('cached-obstacle-bool', '1. 读取缓存字段并转换为 bool。')],
    ),

    method(
      'line-step', 'file-line-follow', 'LineFollower.step(self)',
      '完成一次“读取巡线 GPIO → 判断 → 控制电机”的闭环。', [], output('返回本轮 LineStepResult。'), 136, 143,
      [step('line-step-read', '1. 从 LineSensor 读取四路归一化结果。'), step('line-step-apply', '2. 把读数交给 apply_reading() 执行动作。')],
    ),
    method(
      'line-apply', 'file-line-follow', 'LineFollower.apply_reading(self, reading)',
      '根据一次现成读数选择并执行电机动作，再形成统一巡线结果。',
      [input('reading', '四路传感器归一化读数。')], output('返回 LineStepResult：读数、动作、节点/见线/居中标记。'), 145, 188,
      [
        step('line-apply-decide', '1. 调用 decide_line_action() 得到动作。'),
        step('line-apply-motor', '2. 节点刹车；普通线直行；左右偏差单侧驱动；全白时原地左旋寻线。', 'condition'),
        step('line-apply-debug', '3. 配置 debug_output 时写出读数、动作和电机命令。', 'condition'),
        step('line-apply-result', '4. 分别计算节点、见线和居中状态并构造结果对象。'),
      ],
    ),
    method(
      'line-decide', 'file-line-follow', 'decide_line_action(reading)',
      '按优先级把四路读数分类为节点、左修正、右修正、直行或寻线。',
      [input('reading', '四路巡线归一化读数。')], output('返回 ACTION_NODE/FORWARD/LEFT/RIGHT/SEARCH_LEFT 之一。'), 78, 98,
      [step('decide-node', '1. 节点判断优先，满足时返回 ACTION_NODE。', 'condition'), step('decide-corrections', '2. 依次判断左偏、右偏和内侧双黑直行；其余全白状态返回左旋寻线。', 'condition')],
    ),
    method(
      'line-is-node', 'file-line-follow', 'is_at_node(reading)',
      '识别网格节点宽黑区域，避免把普通中心线误认成节点。', [input('reading', '四路巡线读数。')],
      output('内侧双黑且至少一个外侧也为黑时返回 True。'), 33, 43,
      [step('is-node-expression', '1. 组合内侧双黑与外侧至少一路黑的布尔条件。', 'condition')],
    ),
    method(
      'line-is-seen', 'file-line-follow', 'is_line_seen(reading)',
      '判断四路传感器是否至少一路看见黑线。', [input('reading', '四路巡线读数。')], output('任一路为黑时返回 True。'), 46, 57,
      [step('is-seen-expression', '1. 对四个布尔字段执行逻辑或。', 'condition')],
    ),
    method(
      'line-is-centered', 'file-line-follow', 'is_centered_line(reading)',
      '判断车身是否大致压在普通黑线中心。', [input('reading', '四路巡线读数。')], output('左右内侧传感器同时为黑时返回 True。'), 60, 66,
      [step('is-centered-expression', '1. 对左右内侧字段执行逻辑与。', 'condition')],
    ),

    method(
      'radar-tick', 'file-reverse-radar', 'CachedReverseRadar.tick(self)',
      '按缓存距离推进一次非阻塞蜂鸣状态机。', [], output('无返回值；可能开启、关闭或保持蜂鸣器。'), 42, 66,
      [
        step('radar-distance', '1. 读取后台缓存的 last_distance；无效或超过 100 cm 时停止提示。', 'condition'),
        step('radar-continuous', '2. 15 cm 内直接持续鸣叫。', 'condition'),
        step('radar-pattern-step', '3. 更远距离计算周期与鸣叫时长；到达下次时刻时开启蜂鸣并更新计时。', 'condition'),
        step('radar-off', '4. 当前脉冲到期时关闭蜂鸣。', 'condition'),
      ],
    ),
    method(
      'radar-stop', 'file-reverse-radar', 'CachedReverseRadar.stop(self)',
      '关闭当前蜂鸣并重置下一次提示的时间状态。', [], output('无返回值；结束后 _active 为 False。'), 68, 74,
      [step('radar-stop-off', '1. 仅在当前激活时调用蜂鸣器 off()。', 'condition'), step('radar-stop-reset', '2. 清零激活标记、脉冲截止和下次蜂鸣时刻。')],
    ),
    method(
      'radar-pattern', 'file-reverse-radar', 'CachedReverseRadar._beep_pattern(distance)',
      '把距离分段映射为蜂鸣周期和单次响声时长。', [input('distance', '有效缓存距离，单位 cm。')],
      output('返回 (period, on_seconds)：距离越近周期越短。'), 77, 82,
      [step('radar-pattern-branch', '1. 大于 50、31–50、16–30 cm 分别返回慢、中、快节奏。', 'condition')],
    ),

    method(
      'motor-forward', 'file-motor', 'MotorController.forward(self, left_speed, right_speed)',
      '设置双轮前进方向并应用左右 PWM 速度。', [input('left_speed', '左轮 PWM 占空比 0–100。'), input('right_speed', '右轮 PWM 占空比 0–100。')],
      output('无返回值。'), 42, 56, [step('motor-forward-drive', '1. 把前进方向电平和两侧速度交给 _drive()。')],
    ),
    method(
      'motor-backward', 'file-motor', 'MotorController.backward(self, left_speed, right_speed)',
      '设置双轮后退方向并应用左右 PWM 速度。', [input('left_speed', '左轮 PWM 占空比 0–100。'), input('right_speed', '右轮 PWM 占空比 0–100。')],
      output('无返回值。'), 58, 67, [step('motor-backward-drive', '1. 把后退方向电平和两侧速度交给 _drive()。')],
    ),
    method(
      'motor-left', 'file-motor', 'MotorController.left(self, left_speed, right_speed)',
      '停止左轮、前进右轮，执行弧线左修正。', [input('left_speed', '左轮 PWM，当前方向电平会令左轮停止。'), input('right_speed', '右轮前进 PWM。')],
      output('无返回值。'), 69, 80, [step('motor-left-drive', '1. 把左轮停止、右轮前进电平与速度交给 _drive()。')],
    ),
    method(
      'motor-right', 'file-motor', 'MotorController.right(self, left_speed, right_speed)',
      '前进左轮、停止右轮，执行弧线右修正。', [input('left_speed', '左轮前进 PWM。'), input('right_speed', '右轮 PWM，当前方向电平会令右轮停止。')],
      output('无返回值。'), 82, 91, [step('motor-right-drive', '1. 把左轮前进、右轮停止电平与速度交给 _drive()。')],
    ),
    method(
      'motor-spin-left', 'file-motor', 'MotorController.spin_left(self, left_speed, right_speed)',
      '左轮后退、右轮前进，实现原地左旋。', [input('left_speed', '左轮后退 PWM。'), input('right_speed', '右轮前进 PWM。')],
      output('无返回值。'), 93, 102, [step('motor-spin-left-drive', '1. 把相反轮向和两侧速度交给 _drive()。')],
    ),
    method(
      'motor-spin-right', 'file-motor', 'MotorController.spin_right(self, left_speed, right_speed)',
      '左轮前进、右轮后退，实现原地右旋。', [input('left_speed', '左轮前进 PWM。'), input('right_speed', '右轮后退 PWM。')],
      output('无返回值。'), 104, 113, [step('motor-spin-right-drive', '1. 把相反轮向和两侧速度交给 _drive()。')],
    ),
    method(
      'motor-brake', 'file-motor', 'MotorController.brake(self)',
      '把四个方向引脚拉低，并把左右 PWM 占空比清零。', [], output('无返回值；电机进入停止状态。'), 115, 126,
      [step('motor-brake-gpio', '1. 通过 GPIO 驱动把 IN1–IN4 全部置 LOW。'), step('motor-brake-pwm', '2. 把两路 PWM 占空比改为 0。')],
    ),
    method(
      'motor-drive', 'file-motor', 'MotorController._drive(self, left_forward_pin_value, left_backward_pin_value, right_forward_pin_value, right_backward_pin_value, left_speed, right_speed)',
      '所有运动动作共用的底层方向与速度写入。',
      [input('left_forward_pin_value', '左轮前进方向电平。'), input('left_backward_pin_value', '左轮后退方向电平。'), input('right_forward_pin_value', '右轮前进方向电平。'), input('right_backward_pin_value', '右轮后退方向电平。'), input('left_speed', '左轮 PWM 占空比。'), input('right_speed', '右轮 PWM 占空比。')],
      output('无返回值；速度非法时抛出 ValueError。'), 169, 194,
      [step('motor-drive-validate', '1. 分别校验左右速度。'), step('motor-drive-direction', '2. 通过 GPIO 驱动写入四个方向引脚。'), step('motor-drive-duty', '3. 通过 PWM 驱动更新两侧占空比。')],
    ),
    method(
      'motor-validate-speed', 'file-motor', 'MotorController._validate_speed(name, speed)',
      '阻止超出 PWM 合法范围的速度进入硬件驱动。', [input('name', '用于错误消息的速度字段名。'), input('speed', '待校验占空比。')],
      output('0–100 时无返回值；越界时抛出 ValueError。'), 197, 201,
      [step('motor-speed-range', '1. speed 小于 0 或大于 100 时抛错。', 'error')],
    ),

    method(
      'sensor-read', 'file-line-sensor', 'LineSensor.read(self)',
      '从左到右读取四个 GPIO 输入并转换为黑线布尔读数。', [], output('返回 LineReading。'), 77, 89,
      [step('sensor-gpio-read', '1. 依次调用 GPIO 驱动读取左外、左内、右内、右外原始电平。'), step('sensor-normalize-step', '2. 把四个原始值交给 from_gpio_values() 归一化。')],
    ),
    method(
      'sensor-normalize', 'file-line-sensor', 'LineReading.from_gpio_values(cls, left_outer_value, left_inner_value, right_inner_value, right_outer_value)',
      '按配置的黑线电平把 GPIO 原始值转换成四个布尔字段。',
      [input('left_outer_value', '左外 GPIO 原始值。'), input('left_inner_value', '左内 GPIO 原始值。'), input('right_inner_value', '右内 GPIO 原始值。'), input('right_outer_value', '右外 GPIO 原始值。')],
      output('返回不可变 LineReading；四字段表示对应位置是否检测到黑线。'), 29, 50,
      [step('sensor-black-value', '1. 读取 config.LINE_SENSOR_BLACK_VALUE。'), step('sensor-build-reading', '2. 四个原始值分别与黑线电平比较，构造 LineReading。')],
    ),

    method(
      'buzzer-on', 'file-buzzer', 'Buzzer.on(self)',
      '把蜂鸣器 GPIO 置高电平。', [], output('无返回值；蜂鸣器开始响。'), 60, 62,
      [step('buzzer-on-gpio', '1. 通过 GPIO 驱动向蜂鸣器引脚输出 HIGH。')],
    ),
    method(
      'buzzer-off', 'file-buzzer', 'Buzzer.off(self)',
      '把蜂鸣器 GPIO 置低电平。', [], output('无返回值；蜂鸣器停止响。'), 64, 66,
      [step('buzzer-off-gpio', '1. 通过 GPIO 驱动向蜂鸣器引脚输出 LOW。')],
    ),
  ],
  calls: [
    { id: 'c-nav-init-log', sourceMethodId: 'grid-navigate', sourceStepId: 'nav-initialize', targetMethodId: 'grid-log', kind: 'certain', lane: -5, targetSide: 'right', label: '记录导航启动状态' },
    { id: 'c-nav-blocked-union', sourceMethodId: 'grid-navigate', sourceStepId: 'nav-plan-loop', targetMethodId: 'grid-all-blocked', kind: 'conditional', lane: -4, targetSide: 'right', label: '每轮合并阻塞边' },
    { id: 'c-nav-astar', sourceMethodId: 'grid-navigate', sourceStepId: 'nav-plan-loop', targetMethodId: 'astar-search', kind: 'conditional', lane: -4, targetSide: 'right', label: '每轮重新搜索路径' },
    { id: 'c-nav-no-path-brake', sourceMethodId: 'grid-navigate', sourceStepId: 'nav-no-path', targetMethodId: 'motor-brake', kind: 'conditional', lane: -4, targetSide: 'left', label: '无路径时停车' },
    { id: 'c-nav-no-path-fmt', sourceMethodId: 'grid-navigate', sourceStepId: 'nav-no-path', targetMethodId: 'grid-fmt-node', kind: 'conditional', lane: -3, targetSide: 'right', label: '格式化失败位置' },
    { id: 'c-nav-no-path-log', sourceMethodId: 'grid-navigate', sourceStepId: 'nav-no-path', targetMethodId: 'grid-log', kind: 'conditional', lane: -2, targetSide: 'right', label: '记录无路径结果' },
    { id: 'c-nav-heading', sourceMethodId: 'grid-navigate', sourceStepId: 'nav-prepare-edge', targetMethodId: 'grid-heading-between', kind: 'certain', lane: -5, targetSide: 'right', label: '坐标位移转朝向' },
    { id: 'c-nav-format-path', sourceMethodId: 'grid-navigate', sourceStepId: 'nav-prepare-edge', targetMethodId: 'astar-format-path', kind: 'certain', lane: -4, targetSide: 'right', label: '格式化规划路径' },
    { id: 'c-nav-prepare-fmt', sourceMethodId: 'grid-navigate', sourceStepId: 'nav-prepare-edge', targetMethodId: 'grid-fmt-node', kind: 'certain', lane: -3, targetSide: 'right', label: '格式化规划边端点' },
    { id: 'c-nav-prepare-log', sourceMethodId: 'grid-navigate', sourceStepId: 'nav-prepare-edge', targetMethodId: 'grid-log', kind: 'certain', lane: -2, targetSide: 'right', label: '记录本轮规划' },
    { id: 'c-nav-edge-exec', sourceMethodId: 'grid-navigate', sourceStepId: 'nav-execute-edge', targetMethodId: 'edge-execute', kind: 'certain', lane: -1, targetSide: 'left', label: '执行规划边' },
    { id: 'c-nav-edge-status', sourceMethodId: 'grid-navigate', sourceStepId: 'nav-execute-edge', targetMethodId: 'grid-result-status', kind: 'certain', lane: 0, targetSide: 'right', label: '读取边状态' },
    { id: 'c-nav-edge-fmt', sourceMethodId: 'grid-navigate', sourceStepId: 'nav-execute-edge', targetMethodId: 'grid-fmt-node', kind: 'certain', lane: 1, targetSide: 'right', label: '格式化当前节点' },
    { id: 'c-nav-edge-log', sourceMethodId: 'grid-navigate', sourceStepId: 'nav-execute-edge', targetMethodId: 'grid-log', kind: 'certain', lane: 2, targetSide: 'right', label: '记录边执行结果' },
    { id: 'c-nav-reached-fmt', sourceMethodId: 'grid-navigate', sourceStepId: 'nav-reached', targetMethodId: 'grid-fmt-node', kind: 'conditional', lane: 3, targetSide: 'right', label: '格式化新可信节点' },
    { id: 'c-nav-reached-log', sourceMethodId: 'grid-navigate', sourceStepId: 'nav-reached', targetMethodId: 'grid-log', kind: 'conditional', lane: 4, targetSide: 'right', label: '记录到达节点' },
    { id: 'c-nav-blocked-fmt', sourceMethodId: 'grid-navigate', sourceStepId: 'nav-blocked', targetMethodId: 'grid-fmt-node', kind: 'conditional', lane: 5, targetSide: 'right', label: '格式化阻塞边' },
    { id: 'c-nav-blocked-log', sourceMethodId: 'grid-navigate', sourceStepId: 'nav-blocked', targetMethodId: 'grid-log', kind: 'conditional', lane: -2, targetSide: 'right', label: '记录阻塞与恢复计划' },
    { id: 'c-nav-recover', sourceMethodId: 'grid-navigate', sourceStepId: 'nav-blocked', targetMethodId: 'edge-recover', kind: 'conditional', lane: 0, targetSide: 'left', label: '倒车回原节点' },
    { id: 'c-nav-recovery-status', sourceMethodId: 'grid-navigate', sourceStepId: 'nav-blocked', targetMethodId: 'grid-result-status', kind: 'conditional', lane: -1, targetSide: 'right', label: '读取恢复状态' },
    { id: 'c-nav-recovery-result-log', sourceMethodId: 'grid-navigate', sourceStepId: 'nav-blocked', targetMethodId: 'grid-log', kind: 'conditional', lane: 0, targetSide: 'right', label: '记录恢复结果' },
    { id: 'c-nav-recovery-failed-brake', sourceMethodId: 'grid-navigate', sourceStepId: 'nav-recovery-failed', targetMethodId: 'motor-brake', kind: 'conditional', lane: -2, targetSide: 'left', label: '恢复失败停车' },
    { id: 'c-nav-recovered-heading', sourceMethodId: 'grid-navigate', sourceStepId: 'nav-recovered', targetMethodId: 'grid-result-heading', kind: 'conditional', lane: -5, targetSide: 'right', label: '取得恢复朝向' },
    { id: 'c-nav-recovered-fmt', sourceMethodId: 'grid-navigate', sourceStepId: 'nav-recovered', targetMethodId: 'grid-fmt-node', kind: 'conditional', lane: -4, targetSide: 'right', label: '格式化恢复位置' },
    { id: 'c-nav-recovered-log', sourceMethodId: 'grid-navigate', sourceStepId: 'nav-recovered', targetMethodId: 'grid-log', kind: 'conditional', lane: -3, targetSide: 'right', label: '记录恢复成功' },
    { id: 'c-nav-failed-brake', sourceMethodId: 'grid-navigate', sourceStepId: 'nav-edge-failed', targetMethodId: 'motor-brake', kind: 'certain', lane: 0, targetSide: 'left', label: '未知边状态停车' },
    { id: 'c-nav-failed-fmt', sourceMethodId: 'grid-navigate', sourceStepId: 'nav-edge-failed', targetMethodId: 'grid-fmt-node', kind: 'certain', lane: -2, targetSide: 'right', label: '格式化失败位置' },
    { id: 'c-nav-failed-log', sourceMethodId: 'grid-navigate', sourceStepId: 'nav-edge-failed', targetMethodId: 'grid-log', kind: 'certain', lane: -1, targetSide: 'right', label: '记录未知失败' },
    { id: 'c-nav-arrived-brake', sourceMethodId: 'grid-navigate', sourceStepId: 'nav-arrived', targetMethodId: 'motor-brake', kind: 'certain', lane: 2, targetSide: 'left', label: '到达后停车' },
    { id: 'c-nav-arrived-fmt', sourceMethodId: 'grid-navigate', sourceStepId: 'nav-arrived', targetMethodId: 'grid-fmt-node', kind: 'certain', lane: 0, targetSide: 'right', label: '格式化终点' },
    { id: 'c-nav-arrived-log', sourceMethodId: 'grid-navigate', sourceStepId: 'nav-arrived', targetMethodId: 'grid-log', kind: 'certain', lane: -5, targetSide: 'right', label: '记录到达结果' },
    { id: 'c-fmt-format-path', sourceMethodId: 'grid-fmt-node', sourceStepId: 'fmt-node-format', targetMethodId: 'astar-format-path', kind: 'certain', lane: 0, targetSide: 'right', label: '转换单节点格式' },

    { id: 'c-astar-validate-grid', sourceMethodId: 'astar-search', sourceStepId: 'astar-validate', targetMethodId: 'astar-validate-grid', kind: 'certain', lane: -4, targetSide: 'right', label: '校验网格' },
    { id: 'c-astar-validate-coordinate', sourceMethodId: 'astar-search', sourceStepId: 'astar-validate', targetMethodId: 'astar-validate-coordinate', kind: 'certain', lane: -3, targetSide: 'right', label: '校验起点和终点' },
    { id: 'c-astar-validate-edges', sourceMethodId: 'astar-search', sourceStepId: 'astar-validate', targetMethodId: 'astar-validate-edges', kind: 'certain', lane: -2, targetSide: 'right', label: '校验阻塞边' },
    { id: 'c-astar-init-heuristic', sourceMethodId: 'astar-search', sourceStepId: 'astar-init', targetMethodId: 'astar-heuristic', kind: 'certain', lane: -1, targetSide: 'right', label: '计算起点启发代价' },
    { id: 'c-astar-init-f', sourceMethodId: 'astar-search', sourceStepId: 'astar-init', targetMethodId: 'astar-node-f', kind: 'certain', lane: 0, targetSide: 'right', label: '读取起点总代价属性' },
    { id: 'c-astar-neighbors', sourceMethodId: 'astar-search', sourceStepId: 'astar-neighbors-step', targetMethodId: 'astar-neighbors', kind: 'conditional', lane: 1, targetSide: 'right', label: '枚举合法相邻坐标' },
    { id: 'c-astar-relax-heuristic', sourceMethodId: 'astar-search', sourceStepId: 'astar-relax', targetMethodId: 'astar-heuristic', kind: 'conditional', lane: 2, targetSide: 'right', label: '计算邻居启发代价' },
    { id: 'c-astar-relax-f', sourceMethodId: 'astar-search', sourceStepId: 'astar-relax', targetMethodId: 'astar-node-f', kind: 'conditional', lane: 3, targetSide: 'right', label: '读取邻居总代价属性' },
    { id: 'c-edges-coordinate', sourceMethodId: 'astar-validate-edges', sourceStepId: 'validate-edges-loop', targetMethodId: 'astar-validate-coordinate', kind: 'conditional', lane: 4, targetSide: 'right', label: '校验边的两个端点' },
    { id: 'c-edges-heuristic', sourceMethodId: 'astar-validate-edges', sourceStepId: 'validate-edges-loop', targetMethodId: 'astar-heuristic', kind: 'conditional', lane: 5, targetSide: 'right', label: '确认端点相邻' },

    { id: 'c-edge-exec-log-start', sourceMethodId: 'edge-execute', sourceStepId: 'edge-exec-start', targetMethodId: 'edge-log', kind: 'certain', lane: -5, targetSide: 'right', label: '记录边执行开始' },
    { id: 'c-edge-exec-align', sourceMethodId: 'edge-execute', sourceStepId: 'edge-exec-align', targetMethodId: 'edge-align', kind: 'certain', lane: -4, targetSide: 'right', label: '对准规划朝向' },
    { id: 'c-edge-exec-align-brake', sourceMethodId: 'edge-execute', sourceStepId: 'edge-exec-align', targetMethodId: 'motor-brake', kind: 'conditional', lane: -5, targetSide: 'left', label: '转向失败停车' },
    { id: 'c-edge-exec-align-log', sourceMethodId: 'edge-execute', sourceStepId: 'edge-exec-align', targetMethodId: 'edge-log', kind: 'conditional', lane: -3, targetSide: 'right', label: '记录转向失败' },
    { id: 'c-edge-exec-leave', sourceMethodId: 'edge-execute', sourceStepId: 'edge-exec-leave', targetMethodId: 'edge-leave-node', kind: 'certain', lane: -2, targetSide: 'right', label: '保护性离开节点' },
    { id: 'c-edge-exec-leave-brake', sourceMethodId: 'edge-execute', sourceStepId: 'edge-exec-leave', targetMethodId: 'motor-brake', kind: 'conditional', lane: -5, targetSide: 'left', label: '离点失败停车' },
    { id: 'c-edge-exec-leave-log', sourceMethodId: 'edge-execute', sourceStepId: 'edge-exec-leave', targetMethodId: 'edge-log', kind: 'conditional', lane: -4, targetSide: 'right', label: '记录离点失败' },
    { id: 'c-edge-exec-travel', sourceMethodId: 'edge-execute', sourceStepId: 'edge-exec-travel', targetMethodId: 'edge-travel', kind: 'certain', lane: -3, targetSide: 'right', label: '执行前向行边' },
    { id: 'c-edge-exec-travel-log', sourceMethodId: 'edge-execute', sourceStepId: 'edge-exec-travel', targetMethodId: 'edge-log', kind: 'certain', lane: -2, targetSide: 'right', label: '记录行边结果' },

    { id: 'c-recover-log', sourceMethodId: 'edge-recover', sourceStepId: 'recover-run', targetMethodId: 'edge-log', kind: 'certain', lane: -1, targetSide: 'right', label: '记录恢复开始' },
    { id: 'c-recover-reverse', sourceMethodId: 'edge-recover', sourceStepId: 'recover-run', targetMethodId: 'edge-reverse', kind: 'certain', lane: 0, targetSide: 'right', label: '执行倒车循迹' },
    { id: 'c-recover-success-log', sourceMethodId: 'edge-recover', sourceStepId: 'recover-success', targetMethodId: 'edge-log', kind: 'conditional', lane: 1, targetSide: 'right', label: '记录恢复成功' },
    { id: 'c-recover-failed-brake', sourceMethodId: 'edge-recover', sourceStepId: 'recover-failed', targetMethodId: 'motor-brake', kind: 'certain', lane: 2, targetSide: 'left', label: '恢复失败停车' },
    { id: 'c-recover-failed-log', sourceMethodId: 'edge-recover', sourceStepId: 'recover-failed', targetMethodId: 'edge-log', kind: 'certain', lane: 3, targetSide: 'right', label: '记录恢复失败' },
    { id: 'c-recover-radar-stop', sourceMethodId: 'edge-recover', sourceStepId: 'recover-finally', targetMethodId: 'radar-stop', kind: 'conditional', lane: -5, targetSide: 'left', label: '配置倒车雷达时静音' },

    { id: 'c-align-log-unknown', sourceMethodId: 'edge-align', sourceStepId: 'align-unknown', targetMethodId: 'edge-log', kind: 'conditional', lane: 5, targetSide: 'right', label: '记录跳过转向' },
    { id: 'c-align-log-branch', sourceMethodId: 'edge-align', sourceStepId: 'align-branch', targetMethodId: 'edge-log', kind: 'certain', lane: -4, targetSide: 'right', label: '记录转向选择' },
    { id: 'c-align-rough-turn', sourceMethodId: 'edge-align', sourceStepId: 'align-branch', targetMethodId: 'edge-rough-turn', kind: 'conditional', lane: -3, targetSide: 'right', label: '需要转向时粗转' },
    { id: 'c-rough-spin-left', sourceMethodId: 'edge-rough-turn', sourceStepId: 'rough-spin', targetMethodId: 'motor-spin-left', kind: 'conditional', lane: -4, targetSide: 'left', label: '左向粗转' },
    { id: 'c-rough-spin-right', sourceMethodId: 'edge-rough-turn', sourceStepId: 'rough-spin', targetMethodId: 'motor-spin-right', kind: 'conditional', lane: -2, targetSide: 'left', label: '右向粗转' },
    { id: 'c-rough-brake', sourceMethodId: 'edge-rough-turn', sourceStepId: 'rough-brake', targetMethodId: 'motor-brake', kind: 'certain', lane: 0, targetSide: 'left', label: '粗转结束停车' },

    { id: 'c-leave-log-init', sourceMethodId: 'edge-leave-node', sourceStepId: 'leave-init', targetMethodId: 'edge-log', kind: 'certain', lane: -5, targetSide: 'right', label: '记录离点开始' },
    { id: 'c-leave-sensor', sourceMethodId: 'edge-leave-node', sourceStepId: 'leave-loop', targetMethodId: 'sensor-read', kind: 'conditional', lane: -4, targetSide: 'left', label: '循环读取巡线 GPIO' },
    { id: 'c-leave-apply', sourceMethodId: 'edge-leave-node', sourceStepId: 'leave-loop', targetMethodId: 'line-apply', kind: 'conditional', lane: -4, targetSide: 'right', label: '执行一次循迹动作' },
    { id: 'c-leave-summary', sourceMethodId: 'edge-leave-node', sourceStepId: 'leave-loop', targetMethodId: 'edge-reading-summary', kind: 'conditional', lane: -4, targetSide: 'right', label: '形成读数摘要' },
    { id: 'c-leave-loop-log', sourceMethodId: 'edge-leave-node', sourceStepId: 'leave-loop', targetMethodId: 'edge-log', kind: 'conditional', lane: -3, targetSide: 'right', label: '状态变化时记日志' },
    { id: 'c-leave-forward', sourceMethodId: 'edge-leave-node', sourceStepId: 'leave-classify', targetMethodId: 'motor-forward', kind: 'conditional', lane: -2, targetSide: 'left', label: '起点节点读数时强制前推' },
    { id: 'c-leave-success-log', sourceMethodId: 'edge-leave-node', sourceStepId: 'leave-success', targetMethodId: 'edge-log', kind: 'conditional', lane: -2, targetSide: 'right', label: '记录离点成功' },
    { id: 'c-leave-failed-log', sourceMethodId: 'edge-leave-node', sourceStepId: 'leave-failed', targetMethodId: 'edge-log', kind: 'certain', lane: -1, targetSide: 'right', label: '记录离点失败' },

    { id: 'c-travel-start-log', sourceMethodId: 'edge-travel', sourceStepId: 'travel-start', targetMethodId: 'edge-log', kind: 'certain', lane: -5, targetSide: 'right', label: '记录行边开始' },
    { id: 'c-travel-gate-start', sourceMethodId: 'edge-travel', sourceStepId: 'travel-start', targetMethodId: 'gate-start', kind: 'certain', lane: -4, targetSide: 'right', label: '重置障碍门' },
    { id: 'c-travel-line-step', sourceMethodId: 'edge-travel', sourceStepId: 'travel-loop', targetMethodId: 'line-step', kind: 'conditional', lane: -3, targetSide: 'right', label: '循环执行闭环巡线' },
    { id: 'c-travel-summary', sourceMethodId: 'edge-travel', sourceStepId: 'travel-loop', targetMethodId: 'edge-reading-summary', kind: 'conditional', lane: -3, targetSide: 'right', label: '读数变化时形成摘要' },
    { id: 'c-travel-loop-log', sourceMethodId: 'edge-travel', sourceStepId: 'travel-loop', targetMethodId: 'edge-log', kind: 'conditional', lane: -2, targetSide: 'right', label: '记录巡线状态变化' },
    { id: 'c-travel-center', sourceMethodId: 'edge-travel', sourceStepId: 'travel-node', targetMethodId: 'edge-center-node', kind: 'conditional', lane: -5, targetSide: 'right', label: '节点确认后居中' },
    { id: 'c-travel-stable', sourceMethodId: 'edge-travel', sourceStepId: 'travel-blocked', targetMethodId: 'edge-stable-tracking', kind: 'conditional', lane: -4, targetSide: 'right', label: '确认处于稳定巡线' },
    { id: 'c-travel-gate-check', sourceMethodId: 'edge-travel', sourceStepId: 'travel-blocked', targetMethodId: 'gate-check', kind: 'conditional', lane: -3, targetSide: 'right', label: '读取去抖障碍结果' },
    { id: 'c-travel-block-brake', sourceMethodId: 'edge-travel', sourceStepId: 'travel-blocked', targetMethodId: 'motor-brake', kind: 'conditional', lane: -2, targetSide: 'left', label: '确认阻塞后停车' },
    { id: 'c-travel-block-log', sourceMethodId: 'edge-travel', sourceStepId: 'travel-blocked', targetMethodId: 'edge-log', kind: 'conditional', lane: -1, targetSide: 'right', label: '记录障碍阻塞' },
    { id: 'c-travel-loss-update', sourceMethodId: 'edge-travel', sourceStepId: 'travel-lost', targetMethodId: 'edge-update-loss', kind: 'certain', lane: 0, targetSide: 'right', label: '更新丢线计时' },
    { id: 'c-travel-loss-brake', sourceMethodId: 'edge-travel', sourceStepId: 'travel-lost', targetMethodId: 'motor-brake', kind: 'conditional', lane: 1, targetSide: 'left', label: '持续丢线后停车' },
    { id: 'c-travel-loss-log', sourceMethodId: 'edge-travel', sourceStepId: 'travel-lost', targetMethodId: 'edge-log', kind: 'conditional', lane: 2, targetSide: 'right', label: '记录丢线失败' },
    { id: 'c-travel-timeout-brake', sourceMethodId: 'edge-travel', sourceStepId: 'travel-timeout', targetMethodId: 'motor-brake', kind: 'certain', lane: 3, targetSide: 'left', label: '行边超时停车' },
    { id: 'c-travel-timeout-log', sourceMethodId: 'edge-travel', sourceStepId: 'travel-timeout', targetMethodId: 'edge-log', kind: 'certain', lane: 4, targetSide: 'right', label: '记录行边超时' },

    { id: 'c-reverse-radar-tick', sourceMethodId: 'edge-reverse', sourceStepId: 'reverse-loop', targetMethodId: 'radar-tick', kind: 'conditional', lane: -3, targetSide: 'left', label: '配置雷达时推进蜂鸣状态' },
    { id: 'c-reverse-sensor', sourceMethodId: 'edge-reverse', sourceStepId: 'reverse-loop', targetMethodId: 'sensor-read', kind: 'conditional', lane: 0, targetSide: 'left', label: '循环读取巡线 GPIO' },
    { id: 'c-reverse-apply', sourceMethodId: 'edge-reverse', sourceStepId: 'reverse-loop', targetMethodId: 'edge-apply-reverse', kind: 'conditional', lane: -5, targetSide: 'right', label: '执行反向巡线修正' },
    { id: 'c-reverse-summary', sourceMethodId: 'edge-reverse', sourceStepId: 'reverse-loop', targetMethodId: 'edge-reading-summary', kind: 'conditional', lane: -4, targetSide: 'right', label: '形成恢复读数摘要' },
    { id: 'c-reverse-loop-log', sourceMethodId: 'edge-reverse', sourceStepId: 'reverse-loop', targetMethodId: 'edge-log', kind: 'conditional', lane: -3, targetSide: 'right', label: '记录恢复状态变化' },
    { id: 'c-reverse-center', sourceMethodId: 'edge-reverse', sourceStepId: 'reverse-node', targetMethodId: 'edge-center-node', kind: 'conditional', lane: -2, targetSide: 'right', label: '确认原节点后居中' },
    { id: 'c-reverse-loss-update', sourceMethodId: 'edge-reverse', sourceStepId: 'reverse-lost', targetMethodId: 'edge-update-loss', kind: 'certain', lane: -1, targetSide: 'right', label: '更新恢复丢线计时' },
    { id: 'c-reverse-loss-brake', sourceMethodId: 'edge-reverse', sourceStepId: 'reverse-lost', targetMethodId: 'motor-brake', kind: 'conditional', lane: 2, targetSide: 'left', label: '恢复丢线后停车' },
    { id: 'c-reverse-loss-log', sourceMethodId: 'edge-reverse', sourceStepId: 'reverse-lost', targetMethodId: 'edge-log', kind: 'conditional', lane: 0, targetSide: 'right', label: '记录恢复丢线' },
    { id: 'c-reverse-timeout-brake', sourceMethodId: 'edge-reverse', sourceStepId: 'reverse-timeout', targetMethodId: 'motor-brake', kind: 'certain', lane: 4, targetSide: 'left', label: '恢复超时停车' },
    { id: 'c-reverse-timeout-log', sourceMethodId: 'edge-reverse', sourceStepId: 'reverse-timeout', targetMethodId: 'edge-log', kind: 'certain', lane: -5, targetSide: 'right', label: '记录恢复超时' },

    { id: 'c-reverse-decide', sourceMethodId: 'edge-apply-reverse', sourceStepId: 'reverse-decide', targetMethodId: 'line-decide', kind: 'certain', lane: -2, targetSide: 'right', label: '复用巡线动作判断' },
    { id: 'c-reverse-command-brake', sourceMethodId: 'edge-apply-reverse', sourceStepId: 'reverse-command', targetMethodId: 'motor-brake', kind: 'conditional', lane: -4, targetSide: 'left', label: '节点或寻线状态停车' },
    { id: 'c-reverse-command-backward', sourceMethodId: 'edge-apply-reverse', sourceStepId: 'reverse-command', targetMethodId: 'motor-backward', kind: 'conditional', lane: -2, targetSide: 'left', label: '直退或单侧倒车修正' },
    { id: 'c-reverse-result-node', sourceMethodId: 'edge-apply-reverse', sourceStepId: 'reverse-result', targetMethodId: 'line-is-node', kind: 'certain', lane: -1, targetSide: 'right', label: '计算节点标记' },
    { id: 'c-reverse-result-seen', sourceMethodId: 'edge-apply-reverse', sourceStepId: 'reverse-result', targetMethodId: 'line-is-seen', kind: 'certain', lane: 0, targetSide: 'right', label: '计算见线标记' },
    { id: 'c-reverse-result-centered', sourceMethodId: 'edge-apply-reverse', sourceStepId: 'reverse-result', targetMethodId: 'line-is-centered', kind: 'certain', lane: 1, targetSide: 'right', label: '计算居中标记' },
    { id: 'c-center-forward', sourceMethodId: 'edge-center-node', sourceStepId: 'center-push', targetMethodId: 'motor-forward', kind: 'conditional', lane: 0, targetSide: 'left', label: '短暂前推' },
    { id: 'c-center-brake', sourceMethodId: 'edge-center-node', sourceStepId: 'center-brake', targetMethodId: 'motor-brake', kind: 'certain', lane: 2, targetSide: 'left', label: '节点居中后停车' },

    { id: 'c-gate-obstacle', sourceMethodId: 'gate-check', sourceStepId: 'gate-safe', targetMethodId: 'cached-obstacle-read', kind: 'conditional', lane: -5, targetSide: 'right', label: '读取缓存障碍状态' },

    { id: 'c-line-step-sensor', sourceMethodId: 'line-step', sourceStepId: 'line-step-read', targetMethodId: 'sensor-read', kind: 'certain', lane: -4, targetSide: 'left', label: '读取四路巡线 GPIO' },
    { id: 'c-line-step-apply', sourceMethodId: 'line-step', sourceStepId: 'line-step-apply', targetMethodId: 'line-apply', kind: 'certain', lane: -5, targetSide: 'right', label: '执行动作并形成结果' },
    { id: 'c-line-apply-decide', sourceMethodId: 'line-apply', sourceStepId: 'line-apply-decide', targetMethodId: 'line-decide', kind: 'certain', lane: -4, targetSide: 'right', label: '选择巡线动作' },
    { id: 'c-line-motor-brake', sourceMethodId: 'line-apply', sourceStepId: 'line-apply-motor', targetMethodId: 'motor-brake', kind: 'conditional', lane: -5, targetSide: 'left', label: '节点时停车' },
    { id: 'c-line-motor-forward', sourceMethodId: 'line-apply', sourceStepId: 'line-apply-motor', targetMethodId: 'motor-forward', kind: 'conditional', lane: -4, targetSide: 'left', label: '普通线直行' },
    { id: 'c-line-motor-left', sourceMethodId: 'line-apply', sourceStepId: 'line-apply-motor', targetMethodId: 'motor-left', kind: 'conditional', lane: -3, targetSide: 'left', label: '左偏修正' },
    { id: 'c-line-motor-right', sourceMethodId: 'line-apply', sourceStepId: 'line-apply-motor', targetMethodId: 'motor-right', kind: 'conditional', lane: -2, targetSide: 'left', label: '右偏修正' },
    { id: 'c-line-motor-search', sourceMethodId: 'line-apply', sourceStepId: 'line-apply-motor', targetMethodId: 'motor-spin-left', kind: 'conditional', lane: -1, targetSide: 'left', label: '全白时左旋寻线' },
    { id: 'c-line-result-node', sourceMethodId: 'line-apply', sourceStepId: 'line-apply-result', targetMethodId: 'line-is-node', kind: 'certain', lane: 0, targetSide: 'right', label: '计算节点标记' },
    { id: 'c-line-result-seen', sourceMethodId: 'line-apply', sourceStepId: 'line-apply-result', targetMethodId: 'line-is-seen', kind: 'certain', lane: 1, targetSide: 'right', label: '计算见线标记' },
    { id: 'c-line-result-centered', sourceMethodId: 'line-apply', sourceStepId: 'line-apply-result', targetMethodId: 'line-is-centered', kind: 'certain', lane: 2, targetSide: 'right', label: '计算居中标记' },
    { id: 'c-decide-node', sourceMethodId: 'line-decide', sourceStepId: 'decide-node', targetMethodId: 'line-is-node', kind: 'certain', lane: 3, targetSide: 'right', label: '优先识别节点' },

    { id: 'c-radar-invalid-stop', sourceMethodId: 'radar-tick', sourceStepId: 'radar-distance', targetMethodId: 'radar-stop', kind: 'conditional', lane: 4, targetSide: 'right', label: '无效距离停止提示' },
    { id: 'c-radar-continuous-on', sourceMethodId: 'radar-tick', sourceStepId: 'radar-continuous', targetMethodId: 'buzzer-on', kind: 'conditional', lane: 5, targetSide: 'left', label: '近距离持续鸣叫' },
    { id: 'c-radar-pattern', sourceMethodId: 'radar-tick', sourceStepId: 'radar-pattern-step', targetMethodId: 'radar-pattern', kind: 'certain', lane: -5, targetSide: 'right', label: '计算蜂鸣节奏' },
    { id: 'c-radar-pulse-on', sourceMethodId: 'radar-tick', sourceStepId: 'radar-pattern-step', targetMethodId: 'buzzer-on', kind: 'conditional', lane: -2, targetSide: 'left', label: '开始本次蜂鸣脉冲' },
    { id: 'c-radar-pulse-off', sourceMethodId: 'radar-tick', sourceStepId: 'radar-off', targetMethodId: 'buzzer-off', kind: 'conditional', lane: 0, targetSide: 'left', label: '脉冲到期静音' },
    { id: 'c-radar-stop-off', sourceMethodId: 'radar-stop', sourceStepId: 'radar-stop-off', targetMethodId: 'buzzer-off', kind: 'conditional', lane: 2, targetSide: 'left', label: '激活时关闭蜂鸣器' },

    { id: 'c-motor-forward-drive', sourceMethodId: 'motor-forward', sourceStepId: 'motor-forward-drive', targetMethodId: 'motor-drive', kind: 'certain', lane: -5, targetSide: 'right', label: '写入前进电平与速度' },
    { id: 'c-motor-backward-drive', sourceMethodId: 'motor-backward', sourceStepId: 'motor-backward-drive', targetMethodId: 'motor-drive', kind: 'certain', lane: -4, targetSide: 'right', label: '写入后退电平与速度' },
    { id: 'c-motor-left-drive', sourceMethodId: 'motor-left', sourceStepId: 'motor-left-drive', targetMethodId: 'motor-drive', kind: 'certain', lane: -3, targetSide: 'right', label: '写入左修正电平与速度' },
    { id: 'c-motor-right-drive', sourceMethodId: 'motor-right', sourceStepId: 'motor-right-drive', targetMethodId: 'motor-drive', kind: 'certain', lane: -2, targetSide: 'right', label: '写入右修正电平与速度' },
    { id: 'c-motor-spin-left-drive', sourceMethodId: 'motor-spin-left', sourceStepId: 'motor-spin-left-drive', targetMethodId: 'motor-drive', kind: 'certain', lane: -1, targetSide: 'right', label: '写入左旋电平与速度' },
    { id: 'c-motor-spin-right-drive', sourceMethodId: 'motor-spin-right', sourceStepId: 'motor-spin-right-drive', targetMethodId: 'motor-drive', kind: 'certain', lane: 0, targetSide: 'right', label: '写入右旋电平与速度' },
    { id: 'c-motor-drive-validate', sourceMethodId: 'motor-drive', sourceStepId: 'motor-drive-validate', targetMethodId: 'motor-validate-speed', kind: 'certain', lane: 1, targetSide: 'right', label: '校验左右 PWM 速度' },

    { id: 'c-sensor-normalize', sourceMethodId: 'sensor-read', sourceStepId: 'sensor-normalize-step', targetMethodId: 'sensor-normalize', kind: 'certain', lane: 2, targetSide: 'right', label: '归一化 GPIO 电平' },
  ],
};
